name: linuxserver-your_spotify
services:
  app:
    image: linuxserver/your_spotify:1.12.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: Asia/Kolkata
      APP_URL: ''
      SPOTIFY_PUBLIC: ''
      SPOTIFY_SECRET: ''
      CORS: ''
      MONGO_ENDPOINT: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: APP_URL
          description:
            en_us: The protocol and hostname where the app will be accessed.
        - container: SPOTIFY_PUBLIC
          description:
            en_us: Your Spotify application client ID.
        - container: SPOTIFY_SECRET
          description:
            en_us: Your Spotify application secret.
        - container: CORS
          description:
            en_us: Allowed CORS sources, set to all to allow any source.
        - container: MONGO_ENDPOINT
          description:
            en_us: Set mongodb endpoint address/port.
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - type: bind
        source: /files/.apps/$AppID/config
        target: /config
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: A self-hosted listening statistics tool that integrates with Spotify. It tracks your music habits, fetches data via the Spotify API, and presents it through a modern dashboard. Ideal for music enthusiasts who want personal listening insights. Easy to set up and fully self-hosted.
  tagline:
    en_us: Self-hosted Spotify listening stats dashboard.
  developer: ServaLabs
  author: ServaLabs
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/your_spotify-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/your_spotify-logo.png
  title:
    en_us: Spotify Tracker
  category: LinuxServer.io
  port_map: '80'
