name: big-bear-nocodb
services:
  big-bear-nocodb:
    image: nocodb/nocodb:0.262.2
    container_name: big-bear-nocodb
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://nocodb:nocodb@big-bear-nocodb-db:5432/nocodb
      - NC_AUTH_JWT_SECRET=899499fc-36a0-4131-b077-7bb9f051ac9b
      - NC_REDIS_URL=redis://default:casaos@big-bear-nocodb-redis:6379
    ports:
      - "8669:8080"
    volumes:
      - /files/.apps/$AppID/data:/usr/src/app/data
    networks:
      - big-bear-nocodb-network
    x-casaos:
      volumes:
        - container: /usr/src/app/data
          description:
            en_us: "Container Path: /usr/src/app/data"
      ports:
        - container: "8080"
          description:
            en_us: "Container Port: 8080"
  big-bear-nocodb-db:
    container_name: big-bear-nocodb-db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: nocodb
      POSTGRES_USER: nocodb
      POSTGRES_PASSWORD: nocodb
    volumes:
      - /files/.apps/$AppID/pgdata:/var/lib/postgresql/data
    networks:
      - big-bear-nocodb-network
    x-casaos:
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: "Container Path: /var/lib/postgresql/data"

  big-bear-nocodb-redis:
    image: redis:alpine
    container_name: big-bear-nocodb-redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "casaos"]
    volumes:
      - /files/.apps/$AppID/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - big-bear-nocodb-network
    x-casaos:
      volumes:
        - container: /data
          description:
            en_us: "Container Path: /data"
networks:
  big-bear-nocodb-network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
  main: big-bear-nocodb
  description:
    en_us: |
      Database-App is a powerful no-code platform that converts databases into smart spreadsheets. It enables you to build collaborative tools, internal apps, and dashboards rapidly without coding. Easily connect with PostgreSQL, MySQL, and more, all while retaining control over your data.
  tagline:
    en_us: No-code database, smart spreadsheet
  developer: ServaLabs
  author: ServaLabs
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/nocodb.png
  thumbnail: "https://user-images.githubusercontent.com/86527202/277104231-e2fad786-f211-4dcb-9bd3-aaece83a6783.gif"
  title:
    en_us: Database App
  category: BigBearCasaOS
  port_map: "8669"
