name: big-bear-stirling-pdf
services:
  big-bear-stirling-pdf:
    container_name: big-bear-stirling-pdf
    image: stirlingtools/stirling-pdf:0.44.2
    restart: unless-stopped
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - SECURITY_ENABLE_LOGIN=true
      - SECURITY_INITIALLOGIN_USERNAME=bigbear
      - SECURITY_INITIALLOGIN_PASSWORD=4500733e-a0f8-4605-a712-fd267404956a
      - CSRF_DISABLED=false
      - DEFAULT_LOCALE=en-US
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_US
    volumes:
      - /files/.apps/$AppID/tessdata:/usr/share/tessdata
      - /files/.apps/$AppID/configs:/configs
    ports:
      - "8984:8080"
    x-casaos:
      envs:
        - container: "DOCKER_ENABLE_SECURITY"
          description:
            en_us: "Enable Security Jar for Authentication"
        - container: "SECURITY_ENABLE_LOGIN"
          description:
            en_us: "Enable Login for Authentication"
        - container: "SECURITY_INITIALLOGIN_USERNAME"
          description:
            en_us: "Initial admin username"
        - container: "SECURITY_INITIALLOGIN_PASSWORD"
          description:
            en_us: "Initial admin password"
        - container: "CSRF_DISABLED"
          description:
            en_us: "Disable CSRF Protection"
        - container: "DEFAULT_LOCALE"
          description:
            en_us: "Set Default Locale"
        - container: "INSTALL_BOOK_AND_ADVANCED_HTML_OPS"
          description:
            en_us: "Install Book and Advanced HTML Ops"
        - container: "LANGS"
          description:
            en_us: "Languages"
      volumes:
        - container: "/usr/share/tessdata"
          description:
            en_us: "Container Path: /usr/share/tessdata"
        - container: "/configs"
          description:
            en_us: "Configuration Files Path: /configs"
      ports:
        - container: "8080"
          description:
            en_us: "Container Port: 8080"
x-casaos:
  architectures:
    - amd64
  main: big-bear-stirling-pdf
  description:
    en_us: |
      PDF Editor is a modern, self-hosted tool that allows users to convert, manipulate, and manage PDFs locally via a sleek web interface.
      It supports OCR, localization, and optional book conversion functionality with configurable security settings.
      Ideal for teams or individuals who need robust PDF capabilities without relying on cloud services.
  tagline:
    en_us: Local PDF conversion and editing
  developer: ServaLabs
  author: ServaLabs
  icon: "https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos/Apps/stirling-pdf/logo.png"
  thumbnail: ""
  title:
    en_us: PDF Editor
  category: BigBearCasaOS
  port_map: "8984"