name: big-bear-nextcloud-ls
services:
  big-bear-nextcloud-ls:
    container_name: big-bear-nextcloud-ls
    image: linuxserver/nextcloud:31.0.2
    restart: unless-stopped
    ports:
      - 10443:443
    volumes:
      - /files/.apps/$AppID/config:/config
      - /files/.apps/$AppID/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    x-casaos:
      volumes:
        - container: /config
          description:
            en_us: "Container Path: /config"
        - container: /data
          description:
            en_us: "Container Path: /data"
      ports:
        - container: "443"
          description:
            en_us: "Container Port: 443"
      envs:
        - container: PUID
          description:
            en_us: Process UID
        - container: PGID
          description:
            en_us: Process GID
        - container: TZ
          description:
            en_us: Timezone
x-casaos:
  architectures:
    - amd64
  main: big-bear-nextcloud-ls
  author: ServaLabs
  developer: ServaLabs
  category: BigBearCasaOS
  title:
    en_us: File Sync Server
  description:
    en_us: |
      File Sync Server is a self-hosted cloud storage solution that gives you complete control over your files. 
      It allows secure file access, syncing, and sharing from any device through a user-friendly web interface. 
      Easily collaborate on documents, manage calendars, contacts, and more—all hosted on your private server.
  tagline:
    en_us: A powerful self-hosted platform for syncing and sharing files.
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/nextcloud.png
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/thumbnail.jpg
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/screenshot-3.png
  port_map: "10443"
