name: big-bear-retroarch-web
services:
  big-bear-retroarch-web:
    container_name: big-bear-retroarch-web
    image: inglebard/retroarch-web:latest
    restart: unless-stopped
    environment:
      - ROOT_WWW_PATH="/var/www/html"
    ports:
      - "8617:80"
    x-casaos:
      envs:
        - container: "ROOT_WWW_PATH"
          description:
            en_us: "ROOT_WWW_PATH"
      ports:
        - container: "80"
          description:
            en_us: "Container Port: 80"
x-casaos:
  architectures:
    - amd64
  main: big-bear-retroarch-web
  description:
    en_us: |
      Game Emulator provides access to retro games directly through your browser. Powered by RetroArch Web Player and compiled using Emscripten, it allows seamless emulation of multiple gaming systems. With no client software required, it offers an instant nostalgic gaming experience.
  tagline:
    en_us: Browser-based Retro Gaming Emulator
  developer: ServaLabs
  author: ServaLabs
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos/Apps/retroarch-web/logo.png
  thumbnail: ""
  title:
    en_us: Game Emulator
  category: BigBearCasaOS
  port_map: "8617"
  tips:
    before_install:
      en_us: |
        Before you install read this: https://community.bigbeartechworld.com/t/added-retroarch-web-player-to-bigbearcasaos/2002?u=dragonfire1119
