name: linuxserver-jellyfin
services:
  app:
    image: linuxserver/jellyfin:10.10.6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: Asia/Kolkata
      JELLYFIN_PublishedServerUrl: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: JELLYFIN_PublishedServerUrl
          description:
            en_us: Set the autodiscovery response domain or IP address, include http(s)://.
    ports:
      - target: 8096
        published: 8096
        protocol: tcp
      - target: 8920
        published: 8920
        protocol: tcp
      - target: 7359
        published: 7359
        protocol: udp
      - target: 1900
        published: 1900
        protocol: udp
    volumes:
      - type: bind
        source: /apps/$AppID/
        target: /config
      - type: bind
        source: /files/40 Entertainment
        target: /data/
x-casaos:
  architectures:
    - amd64
  main: app
  author: ServaLabs
  developer: ServaLabs
  category: Entertainment
  description:
    en_us: |
      Media Server is a powerful, open-source platform for organizing, managing, and streaming personal media libraries. It allows you to stream your video, music, and TV shows to a variety of devices from your own server. With full cross-platform support and no premium restrictions, it's ideal for home media enthusiasts seeking control and flexibility.
  tagline:
    en_us: Open-source media server for streaming and managing your content.
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/jellyfin-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/jellyfin-logo.png
  title:
    en_us: Media Server
  port_map: "8096"
