name: big-bear-changedetection
services:
  big-bear-changedetection:
    container_name: big-bear-changedetection
    image: ghcr.io/dgtlmoon/changedetection.io:0.49.6
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /files/.apps/$AppID/datastore:/datastore
    x-casaos:
      ports:
        - container: "5000"
          description:
            en_us: "Container Port: 5000"
x-casaos:
  architectures:
    - amd64
  main: big-bear-changedetection
  description:
    en_us: |
      Change Monitor helps you track changes across websites and online resources with ease. It's a lightweight, self-hosted tool that notifies you when content updates occur.
      Ideal for tracking product restocks, document edits, or any web content change. Stay informed in real-time with a simple web interface and flexible notification options.
      No cloud dependency – your data stays with you.
  tagline:
    en_us: Website content monitoring tool.
  developer: ServaLabs
  author: ServaLabs
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/changedetection-io.png
  thumbnail: ""
  title:
    en_us: Change Detector
  category: BigBearCasaOS
  port_map: "5000"
