name: big-bear-immich-aio-alpine
services:
  big-bear-immich-aio-alpine:
    container_name: big-bear-immich-aio-alpine
    image: ghcr.io/imagegenius/immich:1.129.0-alpine
    ports:
      - 2283:8080
    volumes:
      - /files/.apps/$AppID/config:/config
      - /files/.apps/$AppID/photos:/usr/src/app/photos
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - DB_HOSTNAME=big-bear-immich-db
      - DB_USERNAME=casaos
      - DB_PASSWORD=casaos
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=big-bear-immich-redis
      - DB_PORT=5432
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - MACHINE_LEARNING_GPU_ACCELERATION=
      - MACHINE_LEARNING_WORKERS=1
      - MACHINE_LEARNING_WORKER_TIMEOUT=120
    depends_on:
      - big-bear-immich-redis
      - big-bear-immich-db
    restart: unless-stopped
    networks:
      - big_bear_immich_network
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: "Process UID"
        - container: PGID
          description:
            en_us: "Process GID"
        - container: TZ
          description:
            en_us: "Timezone"
        - container: DB_HOSTNAME
          description:
            en_us: "Database Hostname"
        - container: DB_USERNAME
          description:
            en_us: "Database Username"
        - container: DB_PASSWORD
          description:
            en_us: "Database Password"
        - container: DB_DATABASE_NAME
          description:
            en_us: "Database Name"
        - container: DB_PORT
          description:
            en_us: "Database Port"
        - container: REDIS_HOSTNAME
          description:
            en_us: "Redis Hostname"
        - container: REDIS_PORT
          description:
            en_us: "Redis Port"
        - container: REDIS_PASSWORD
          description:
            en_us: "Redis Password"
        - container: MACHINE_LEARNING_GPU_ACCELERATION
          description:
            en_us: "Machine Learning GPU Acceleration"
        - container: MACHINE_LEARNING_WORKERS
          description:
            en_us: "Machine Learning Workers"
        - container: MACHINE_LEARNING_WORKER_TIMEOUT
          description:
            en_us: "Machine Learning Worker Timeout"
      volumes:
        - container: /config
          description:
            en_us: "Container Path: /config"
        - container: /photos
          description:
            en_us: "Container Path: /photos"
      ports:
        - container: "3001"
          description:
            en_us: "Container Port: 3001"
  big-bear-immich-redis:
    container_name: big-bear-immich-redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always
    networks:
      - big_bear_immich_network
  big-bear-immich-db:
    container_name: big-bear-immich-db
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_PASSWORD: casaos
      POSTGRES_USER: casaos
      POSTGRES_DB: immich
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - /files/.apps/$AppID/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - big_bear_immich_network
    x-casaos:
      envs:
        - container: POSTGRES_PASSWORD
          description:
            en_us: "Database Password"
        - container: POSTGRES_USER
          description:
            en_us: "Database Username"
        - container: POSTGRES_DB
          description:
            en_us: "Database Name"
        - container: PG_DATA
          description:
            en_us: "Container Path: /var/lib/postgresql/data"
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: "Container Path: /var/lib/postgresql/data"
networks:
  big_bear_immich_network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
  main: big-bear-immich-aio-alpine
  author: ServaLabs
  developer: ServaLabs
  category: BigBearCasaOS
  description:
    en_us: Gallery is a self-hosted, privacy-focused photo and video management system. It allows secure, organized storage of media files with machine learning capabilities for face and object recognition. Ideal for personal cloud media archiving and family sharing.
  tagline:
    en_us: Self-hosted photo and video gallery
  title:
    en_us: Gallery
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
  thumbnail: ""
  port_map: "2283"