name: swingmusic
services:
    swingmusic:
        cpu_shares: 90
        command: []
        container_name: music-player
        deploy:
            resources:
                limits:
                    memory: "16524509184"
        hostname: swingmusic
        image: ghcr.io/swingmx/swingmusic:v1.4.8
        labels:
            icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/SwingMusic/icon.png
        networks:
            default: null
        ports:
            - mode: ingress
              target: 1970
              published: "1970"
              protocol: tcp
        restart: unless-stopped
        volumes:
            - type: bind
              source: /lab/Apps/Music Player
              target: /config
            - type: bind
              source: /lab/40 Entertainment/43 Music
              target: /music
networks:
    default:
        name: swingmusic_default
x-casaos:
    architectures:
        - amd64
    author: CasaOS Team
    category: Media
    description:
        en_us: |
            Swing Music is a beautifully designed, self-hosted music streaming server. Like a cooler Spotify ... but bring your own music.
        zh_cn: |
            Swing Music 是一款设计精美的自托管音乐流媒体服务器。就像更酷的 Spotify......但可以带来你自己的音乐。
    developer: SwingMX
    hostname: ""
    icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/SwingMusic/icon.png
    index: /
    is_uncontrolled: false
    main: swingmusic
    port_map: "1970"
    scheme: http
    screenshot_link:
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/SwingMusic/screenshot-1.png
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/SwingMusic/screenshot-2.png
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/SwingMusic/screenshot-3.png
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/SwingMusic/screenshot-4.png
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/SwingMusic/screenshot-5.png
    store_app_id: swingmusic
    tagline:
        en_us: Swing Music is a beautifully designed, self-hosted music streaming server. Like a cooler Spotify ... but bring your own music.
        zh_cn: Swing Music 是一款设计精美的自托管音乐流媒体服务器。就像更酷的 Spotify......但可以带来你自己的音乐。
    tips:
        before_install:
            en_us: |
                When you first start Swing Music, it will ask you to pick music directory: Where do you want to look for music?
                select "Specific directories" Option, and select "/music" and rescan.
            zh_cn: |
                首次启动 Swing Music 时，它会要求您选择音乐目录：您想在哪里查找音乐？
                选择“特定目录”选项，然后选择“/music”并重新扫描。
    title:
        custom: Music Player
        en_us: Swing Music
        zh_cn: Swing Music
