name: big-bear-appsmith

services:
  app:
    image: appsmith/appsmith-ce:v1.53.1
    container_name: appsmith
    ports:
      - "1080:80"
      - "10443:443"
    volumes:
      - /files/.apps/$AppID/stacks:/appsmith-stacks
    restart: unless-stopped
    x-casaos:
      volumes:
        - container: /appsmith-stacks
          description:
            en_us: "Container Path: /appsmith-stacks"
      ports:
        - container: "1080"
          description:
            en_us: "Container Port: 1080"
        - container: "10443"
          description:
            en_us: "Container Port: 10443"

x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: |
      Admin-Builder is a low-code platform to create internal tools, dashboards, and CRUD apps effortlessly. 
      It integrates with multiple data sources like PostgreSQL, REST APIs, and Google Sheets, empowering teams to build quickly. 
      With a rich component library and drag-and-drop UI, you can create responsive apps without needing full-stack development skills.
  tagline:
    en_us: Internal Tool Builder
  developer: ServaLabs
  author: ServaLabs
  icon: https://cdn.jsdelivr.net/gh/appsmithorg/appsmith/static/logo.png
  thumbnail: ""
  title:
    en_us: App Builder
  category: BigBearCasaOS
  port_map: "1080"
