name: linuxserver-snapdrop
services:
  app:
    image: linuxserver/snapdrop:version-b8b78cc2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: Asia/Kolkata
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - type: bind
        source: /files/.apps/$AppID/config
        target: /config
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: |
      File Sharing provides seamless, instant file transfer across devices via a browser-based interface.
      Inspired by Airdrop, it enables local peer-to-peer sharing without any account or setup. It's fast, secure, and doesn't rely on internet connectivity.
      Perfect for quickly exchanging photos, documents, or other files between laptops, phones, and tablets.
  tagline:
    en_us: Simple, local file sharing via your browser.
  developer: ServaLabs
  author: ServaLabs
  icon: https://raw.githubusercontent.com/snapdrop/snapdrop/master/client/images/logo_transparent_512x512.png
  thumbnail: https://raw.githubusercontent.com/snapdrop/snapdrop/master/client/images/logo_transparent_512x512.png
  title:
    en_us: File Sharing
  category: LinuxServer.io
  port_map: "80"
