name: big-bear-n8n
services:
  app:
    container_name: n8n
    image: n8nio/n8n:1.84.1
    restart: unless-stopped
    ports:
      - 5678:5678
    links:
      - db-n8n
    volumes:
      - /files/.apps/$AppID/n8n:/home/node/.n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=db-n8n
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=bigbearcasaos
      - DB_POSTGRESDB_PASSWORD=bigbearcasaos
    depends_on:
      db-n8n:
        condition: service_healthy
    x-casaos:
      envs:
        - container: DB_TYPE
          description:
            en_us: "Database type: postgresdb"
      volumes:
        - container: /home/node/.n8n
          description:
            en_us: "Container Path: /home/node/.n8n"
      ports:
        - container: "5678"
          description:
            en_us: "Container Port: 5678"
  db-n8n:
    container_name: db-n8n
    image: postgres:14.2
    restart: on-failure
    volumes:
      - /files/.apps/$AppID/pgdata:/var/lib/postgresql/data
      - /files/.apps/$AppID/init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    environment:
      - POSTGRES_PASSWORD=bigbearcasaos
      - POSTGRES_USER=bigbearcasaos
      - POSTGRES_DB=n8n
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U bigbearcasaos -d n8n"]
      interval: 5s
      timeout: 5s
      retries: 10
    x-casaos:
      envs:
        - container: POSTGRES_PASSWORD
          description:
            en_us: "Database password: bigbearcasaos"
        - container: POSTGRES_USER
          description:
            en_us: "Database user: bigbearcasaos"
        - container: POSTGRES_DB
          description:
            en_us: "Database type: postgresdb"
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: "Container Path: /var/lib/postgresql/data"
        - container: /docker-entrypoint-initdb.d/init-data.sh
          description:
            en_us: "Container Path: /docker-entrypoint-initdb.d/init-data.sh"
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Workflow Automation is a modern, self-hosted platform to automate tasks, integrate services, and orchestrate processes with no-code/low-code logic. Ideal for business operations and productivity flows, it supports webhooks, scheduling, and third-party APIs with a visual interface.
  tagline:
    en_us: Self-hosted no-code workflow automation
  developer: ServaLabs
  author: ServaLabs
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/n8n.png
  thumbnail: ""
  title:
    en_us: Workflow Automation
  category: Automation
  port_map: "5678"
  tips:
    before_install:
      en_us: |
        Run this script:

        ```
        bash -c "$(wget -qLO - https://raw.githubusercontent.com/bigbeartechworld/big-bear-scripts/master/generate-n8n-init-data/run.sh)"
        ```