name: big-bear-cyberchef
services:
  big-bear-cyberchef:
    container_name: big-bear-cyberchef
    image: ghcr.io/gchq/cyberchef:10.19.4
    restart: unless-stopped
    ports:
      - "8556:80"
    x-casaos:
      ports:
        - container: "80"
          description:
            en_us: "Container Port: 80"
x-casaos:
  architectures:
    - amd64
  main: big-bear-cyberchef
  author: ServaLabs
  developer: ServaLabs
  category: BigBearCasaOS
  description:
    en_us: |
      Data-Toolkit is a browser-based utility suite for analyzing and transforming data. It enables powerful operations such as encoding, decoding, encryption, compression, and pattern recognition. 
      With support for formats like Base64, XOR, AES, and more, it's an essential tool for developers and analysts needing to dissect or manipulate raw input.
  tagline:
    en_us: Web-based Data Analysis Toolkit
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/cyberchef.png
  thumbnail: ""
  title:
    en_us: Data Toolkit
  port_map: "8556"