name: big-bear-onlyoffice
services:
  app:
    image: onlyoffice/documentserver:8.3.2
    container_name: documentserver
    ports:
      - "7400:80"
    volumes:
      - /apps/$AppID/logs:/var/log/onlyoffice
      - /apps/$AppID/data:/var/www/onlyoffice/Data
      - /apps/$AppID/lib:/var/lib/onlyoffice
      - /apps/$AppID/rabbitmq:/var/lib/rabbitmq
      - /apps/$AppID/redis:/var/lib/redis
      - /apps/$AppID/db:/var/lib/postgresql
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=admin
      - JWT_HEADER=Authorization
    x-casaos:
      volumes:
        - container: /var/log/onlyoffice
          description:
            en_us: "Container Path: /var/log/onlyoffice"
        - container: /var/www/onlyoffice/Data
          description:
            en_us: "Container Path: /var/www/onlyoffice/Data"
        - container: /var/lib/onlyoffice
          description:
            en_us: "Container Path: /var/lib/onlyoffice"
        - container: /var/lib/rabbitmq
          description:
            en_us: "Container Path: /var/lib/rabbitmq"
        - container: /var/lib/redis
          description:
            en_us: "Container Path: /var/lib/redis"
        - container: /var/lib/postgresql
          description:
            en_us: "Container Path: /var/lib/postgresql"
      ports:
        - container: "80"
          description:
            en_us: "Container Port: 80"
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: A web-based collaborative office suite that supports documents, spreadsheets, and presentations. Ideal for teams, it enables real-time co-authoring and editing in a private cloud environment. This app is perfect for users who want a powerful alternative to traditional office software, hosted entirely on their own infrastructure.
  tagline:
    en_us: Collaborative Office Suite
  developer: ServaLabs
  author: ServaLabs
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/onlyoffice.png
  thumbnail: ""
  title:
    en_us: Office Suite
  category: Office
  port_map: "7400"
