name: node-red
services:
  node-red:
    image: nodered/node-red:4.0.8
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: host
    ports:
      - target: 1880
        published: "1880"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /files/.apps/$AppID/data
        target: /data
    x-casaos:
      ports:
        - container: "1880"
          description:
            en_us: ""
      volumes:
        - container: /data
          description:
            en_us: ""
    container_name: node-red
x-casaos:
  architectures:
    - amd64
  main: node-red
  author: ServaLabs
  category: Developer
  description:
    en_us: |
      Flow-Automator is a powerful low-code development tool for creating event-driven workflows. It provides a browser-based interface to design, deploy, and manage integrations between hardware devices, APIs, and services. With its visual editor and extensive node library, it's ideal for rapid prototyping and automating IoT or backend systems. Flow-Automator runs locally, giving you full control over your automation environment.
  developer: ServaLabs
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Node-RED/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Node-RED/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Node-RED/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Node-RED/screenshot-3.png
  tagline:
    en_us: Visual automation for devices, APIs, and services
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Node-RED/thumbnail.png
  tips: {}
  title:
    en_us: Flow-Automator
  index: /
  port_map: "1880"
