name: linuxserver-fail2ban
services:
  app:
    image: linuxserver/fail2ban:1.1.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: Asia/Kolkata
      VERBOSITY: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: VERBOSITY
          description:
            en_us: Set the container log verbosity. Valid options are -v, -vv, -vvv, -vvvv, or leaving the value blank or not setting the variable.
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /files/.apps/$AppID/config
        target: /config
      - type: bind
        source: /files/.apps/$AppID/var-log
        target: /var/log:ro
      - type: bind
        source: /files/.apps/$AppID/remotelogs-airsonic
        target: /remotelogs/airsonic:ro
      - type: bind
        source: /files/.apps/$AppID/remotelogs-apache2
        target: /remotelogs/apache2:ro
      - type: bind
        source: /files/.apps/$AppID/remotelogs-authelia
        target: /remotelogs/authelia:ro
      - type: bind
        source: /files/.apps/$AppID/remotelogs-emby
        target: /remotelogs/emby:ro
      - type: bind
        source: /files/.apps/$AppID/remotelogs-filebrowser
        target: /remotelogs/filebrowser:ro
      - type: bind
        source: /files/.apps/$AppID/remotelogs-homeassistant
        target: /remotelogs/homeassistant:ro
      - type: bind
        source: /files/.apps/$AppID/remotelogs-lighttpd
        target: /remotelogs/lighttpd:ro
      - type: bind
        source: /files/.apps/$AppID/remotelogs-nextcloud
        target: /remotelogs/nextcloud:ro
      - type: bind
        source: /files/.apps/$AppID/remotelogs-nginx
        target: /remotelogs/nginx:ro
      - type: bind
        source: /files/.apps/$AppID/remotelogs-nzbget
        target: /remotelogs/nzbget:ro
      - type: bind
        source: /files/.apps/$AppID/remotelogs-overseerr
        target: /remotelogs/overseerr:ro
      - type: bind
        source: /files/.apps/$AppID/remotelogs-prowlarr
        target: /remotelogs/prowlarr:ro
      - type: bind
        source: /files/.apps/$AppID/remotelogs-radarr
        target: /remotelogs/radarr:ro
      - type: bind
        source: /files/.apps/$AppID/remotelogs-sabnzbd
        target: /remotelogs/sabnzbd:ro
      - type: bind
        source: /files/.apps/$AppID/remotelogs-sonarr
        target: /remotelogs/sonarr:ro
      - type: bind
        source: /files/.apps/$AppID/remotelogs-unificontroller
        target: /remotelogs/unificontroller:ro
      - type: bind
        source: /files/.apps/$AppID/remotelogs-vaultwarden
        target: /remotelogs/vaultwarden:ro
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Attack Protector automates the detection and banning of malicious IP addresses that trigger authentication failures. It integrates with a variety of log sources and offers protection for services like SSH, web apps, and more. This daemon enhances server security by dynamically updating firewall rules to block threats in real time.
  tagline:
    en_us: Intelligent IP banning for brute-force protection.
  developer: ServaLabs
  author: ServaLabs
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/fail2ban-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/fail2ban-logo.png
  title:
    en_us: Attack Protector
  category: LinuxServer.io
  port_map: '80'
