name: adguard-home
services:
  adguard-home:
    image: adguard/adguardhome:v0.107.55
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 53
        published: "531"
        protocol: tcp
      - target: 53
        published: "531"
        protocol: udp
      - target: 3000
        published: "3001"
        protocol: tcp
      - target: 853
        published: "853"
        protocol: tcp
      - target: 784
        published: "784"
        protocol: udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /files/.apps/$AppID/work
        target: /opt/adguardhome/work
      - type: bind
        source: /files/.apps/$AppID/conf
        target: /opt/adguardhome/conf
    x-casaos:
      ports:
        - container: "53"
          description:
            en_us: ""
        - container: "53"
          description:
            en_us: ""
        - container: "3000"
          description:
            en_us: ""
        - container: "853"
          description:
            en_us: ""
        - container: "784"
          description:
            en_us: ""
      volumes:
        - container: /opt/adguardhome/work
          description:
            en_us: ""
        - container: /opt/adguardhome/conf
          description:
            en_us: ""
    container_name: adguard-home
x-casaos:
  architectures:
    - amd64
  main: adguard-home
  author: ServaLabs
  developer: ServaLabs
  category: Network
  description:
    en_us: |
      Network Firewall is a self-hosted, DNS-based filtering solution that blocks ads, trackers, and malicious domains across all devices on your local network. It functions as a central DNS server, protecting all connected clients without needing to install individual blockers. With support for encrypted DNS protocols like DoH and DoT, and a user-friendly interface for rule customization and analytics, it provides robust privacy and browsing performance for your entire home.
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-3.png
  tagline:
    en_us: Blocking ads & tracking Network-wide
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/thumbnail.png
  tips: {}
  title:
    en_us: Network Firewall
  index: /
  port_map: "3001"
