name: jdownloader2
services:
  jdownloader2:
    image: jlesage/jdownloader-2:latest
    restart: unless-stopped
    x-casaos:
      volumes:
        - container: /config
          description:
            en_us: Configs
        - container: /output
          description:
            en_us: Downloads
      envs:
        - container: TZ
          description:
            en_us: TimeZone
        - container: USER_ID
          description:
            en_us: ID of the user the application runs as. See User/Group IDs to better understand when this should be set.
        - container: GROUP_ID
          description:
            en_us: ID of the group the application runs as. See User/Group IDs to better understand when this should be set.
        - container: MYJDOWNLOADER_EMAIL
          description:
            en_us: Email address of the MyJDownloader account to use. This can also be configured via the JDownloader GUI.
        - container: MYJDOWNLOADER_PASSWORD
          description:
            en_us: Password of the MyJDownloader account to use. This can also be configured via the JDownloader GUI.
        - container: MYJDOWNLOADER_DEVICE_NAME
          description:
            en_us: The name of this JDownloader instance. This can also be configured via the JDownloader GUI.
        - container: JDOWNLOADER_HEADLESS
          description:
            en_us: Run JDownloader in headless mode (no GUI). Use MyJDownloader to control it remotely.
      ports:
        - container: "5800"
          description:
            en_us: Access the application's GUI via web interface. Optional if web interface access is not needed.
        - container: "5900"
          description:
            en_us: Access the application's GUI via the VNC protocol. Optional if VNC access is not needed.
        - container: "3129"
          description:
            en_us: Used by MyJDownloader for direct connection. Must match host port (3129) if enabled.
    environment:
      - USER_ID=$PUID
      - GROUP_ID=$PGID
      - TZ=Asia/Kolkata
      - MYJDOWNLOADER_EMAIL=$MYJDOWNLOADER_EMAIL
      - MYJDOWNLOADER_PASSWORD=$MYJDOWNLOADER_PASSWORD
      - MYJDOWNLOADER_DEVICE_NAME=$MYJDOWNLOADER_DEVICE_NAME
      - JDOWNLOADER_HEADLESS=$JDOWNLOADER_HEADLESS
    ports:
      - target: 5800
        published: "5800"
        protocol: tcp
      - target: 5900
        published: "5900"
        protocol: tcp
      - target: 3129
        published: "3129"
        protocol: tcp
    volumes:
      - type: bind
        source: /files/.apps/$AppID/config
        target: /config
      - type: bind
        source: /files/Downloads
        target: /output
    container_name: jdownloader2
x-casaos:
  architectures:
    - amd64
  main: jdownloader2
  author: ServaLabs
  developer: ServaLabs
  category: Utilities
  description:
    en_us: |
      Downloader is a powerful, open-source tool for managing and automating file downloads from the web. 
      It supports multiple download sources, automatic extraction of archives, bandwidth control, and more.
      Remote control via MyJDownloader allows managing downloads from anywhere. 
      Ideal for power users who need flexibility and performance in their downloading workflow.
  tagline:
    en_us: Smart download automation for all your needs
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/JDownloader2/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/JDownloader2/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/JDownloader2/screenshot-2.jpg
  port_map: "5800"
  scheme: http
  store_app_id: jdownloader2
  title:
    en_us: Internet Downloader