name: big-bear-nextcloud-smb

services:
  big-bear-nextcloud-smb:
    container_name: big-bear-nextcloud-smb
    image: bigbeartechworld/big-bear-nextcloud-with-smbclient:0.0.7
    restart: unless-stopped
    ports:
      - 7580:80
    volumes:
      - /files/.apps/$AppID/html:/var/www/html
    environment:
      - POSTGRES_HOST=big-bear-nextcloud-smb-db
      - REDIS_HOST=big-bear-nextcloud-smb-redis
      - POSTGRES_PASSWORD=casaos
      - POSTGRES_USER=casaos
      - POSTGRES_DB=nextcloud
      - NEXTCLOUD_ADMIN_USER=casaos
      - NEXTCLOUD_ADMIN_PASSWORD=casaos
      - TRUSTED_PROXIES=
      - OVERWRITEPROTOCOL=http
      - PHP_MEMORY_LIMIT=1024M
      - PHP_UPLOAD_LIMIT=1024M
    depends_on:
      big-bear-nextcloud-smb-db:
        condition: service_healthy
      big-bear-nextcloud-smb-redis:
        condition: service_healthy
    networks:
      - big_bear_nextcloud_network
    x-casaos:
      volumes:
        - container: /var/www/html
          description:
            en_us: "Container Path: /var/www/html"
      envs:
        - container: POSTGRES_HOST
          description:
            en_us: Database host
        - container: REDIS_HOST
          description:
            en_us: Redis host
        - container: POSTGRES_PASSWORD
          description:
            en_us: Database password
        - container: POSTGRES_USER
          description:
            en_us: Database user
        - container: POSTGRES_DB
          description:
            en_us: Database type
        - container: NEXTCLOUD_ADMIN_USER
          description:
            en_us: Nextcloud admin user
        - container: NEXTCLOUD_ADMIN_PASSWORD
          description:
            en_us: Nextcloud admin password
        - container: TRUSTED_PROXIES
          description:
            en_us: Trusted proxies
        - container: OVERWRITEPROTOCOL
          description:
            en_us: Overwrite protocol
        - container: PHP_UPLOAD_LIMIT
          description:
            en_us: PHP upload limit
      ports:
        - container: "7580"
          description:
            en_us: "Container Port: 7580"

  big-bear-nextcloud-smb-db:
    container_name: big-bear-nextcloud-smb-db
    image: postgres:14.2
    restart: unless-stopped
    volumes:
      - /files/.apps/$AppID/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=casaos
      - POSTGRES_USER=casaos
      - POSTGRES_DB=nextcloud
    networks:
      - big_bear_nextcloud_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U casaos -d nextcloud"]
      interval: 10s
      timeout: 5s
      retries: 5
    x-casaos:
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: "Container Path: /var/lib/postgresql/data"
      envs:
        - container: POSTGRES_PASSWORD
          description:
            en_us: Database password
        - container: POSTGRES_USER
          description:
            en_us: Database user
        - container: POSTGRES_DB
          description:
            en_us: Database type

  big-bear-nextcloud-smb-redis:
    container_name: big-bear-nextcloud-smb-redis
    user: "1000:1000"
    image: redis:6.2.6
    restart: on-failure
    volumes:
      - /files/.apps/$AppID/redis:/data
    networks:
      - big_bear_nextcloud_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    x-casaos:
      volumes:
        - container: /data
          description:
            en_us: "Container Path: /data"
      ports:
        - container: "6379"
          description:
            en_us: "Container Port: 6379"

  big-bear-nextcloud-smb-cron:
    container_name: big-bear-nextcloud-smb-cron
    image: bigbeartechworld/big-bear-nextcloud-with-smbclient:0.0.7
    restart: on-failure
    volumes:
      - /files/.apps/$AppID/html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      big-bear-nextcloud-smb-db:
        condition: service_healthy
      big-bear-nextcloud-smb-redis:
        condition: service_healthy
    networks:
      - big_bear_nextcloud_network
    x-casaos:
      volumes:
        - container: /var/www/html
          description:
            en_us: "Container Path: /var/www/html"

networks:
  big_bear_nextcloud_network:
    driver: bridge

x-casaos:
  architectures:
    - amd64
  main: big-bear-nextcloud-smb
  description:
    en_us: A private cloud platform to store, sync, and share data securely from any device. This solution includes file sync, calendar, contacts, and collaborative tools, hosted on your own server. It integrates with database and caching services and supports SMB client features.
  tagline:
    en_us: A secure and powerful private cloud
  developer: ServaLabs
  author: ServaLabs
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/nextcloud.png
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/thumbnail.jpg
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/screenshot-3.png
  title:
    en_us: Private Cloud
  category: BigBearCasaOS
  port_map: "7580"
