name: matter-server
services:
  app:
    image: ghcr.io/home-assistant-libs/python-matter-server:7.0.1
    restart: unless-stopped
    network_mode: host
    volumes:
      - type: bind
        source: /DATA/AppData/matter-server/data
        target: /data
      - type: bind
        source: /run/dbus
        target: /run/dbus
        read_only: true
    security_opt:
      - apparmor:unconfined
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: A Matter Controller Server over WebSockets using the official Matter (formerly CHIP) SDK as a base and provides both a server and client implementation. The goal of this project is primary to have Matter support in Home Assistant but its universal approach makes it suitable to be used in other projects too.
  tagline:
    en_us: Matter support in Home Assistant
  developer: Home Assistant
  author: WisdomSky
  icon: https://avatars.githubusercontent.com/u/61027988
  thumbnail: https://avatars.githubusercontent.com/u/61027988
  category: Coolstore
  title:
    en_us: Matter Server
