name: rocket-chat
services:
  app:
    image: rocket.chat:7.4
    restart: unless-stopped
    environment:
      MONGO_OPLOG_URL: mongodb://db:27017/local
    depends_on:
      - db
    ports:
      - target: 3000
        published: '3000'
        protocol: tcp
  db:
    image: mongo:6.0.21
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: Asia/Kolkata
    volumes:
      - type: bind
        source: /files/.apps/$AppID/configdb
        target: /data/configdb
      - type: bind
        source: /files/.apps/$AppID/db
        target: /data/db
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: |
      Chat Suite is a modern, self-hosted communication platform designed for secure, real-time messaging across teams and organizations. It supports web, desktop, and mobile devices, offering robust features such as channels, direct messages, integrations, and more. Ideal for businesses seeking data sovereignty and a customizable alternative to cloud chat services.
  tagline:
    en_us: A secure, real-time messaging solution for teams and organizations.
  developer: ServaLabs
  author: ServaLabs
  icon: https://static.cdnlogo.com/logos/r/32/rocket-chat.svg
  thumbnail: https://static.cdnlogo.com/logos/r/32/rocket-chat.svg
  title:
    en_us: Chat Suite
  tips:
    before_install:
      en_us: |
        ### Note

        After installation, please wait 1–5 minutes before opening the Web UI. Opening it too soon may cause the app to crash and require reinstallation.
  category: Chat
  port_map: '3000'