name: immich
services:
  immich-server:
    deploy:
      resources:
        reservations:
          memory: 1024M
    container_name: immich-server
    hostname: immich-server
    image: altran1502/immich-server:v1.123.0
    volumes:
      - /files/.apps/$AppID/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_DATABASE_NAME: immich
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false
    networks:
      - immich
  immich-machine-learning:
    container_name: immich-machine-learning
    hostname: immich-machine-learning
    image: altran1502/immich-machine-learning:v1.123.0
    environment:
      DB_DATABASE_NAME: immich
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
    restart: unless-stopped
    volumes:
      - /files/.apps/$AppID/model-cache:/cache
    healthcheck:
      disable: false
    networks:
      - immich

  redis:
    container_name: immich-redis
    hostname: immich-redis
    image: docker.io/redis:6.2-alpine@sha256
    healthcheck:
      test: redis-cli ping || exit 1
    volumes:
      - /files/.apps/$AppID/redis:/data
    restart: unless-stopped
    networks:
      - immich
  database:
    container_name: immich-postgres
    hostname: immich-postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - /files/.apps/$AppID/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='immich' --username='postgres' || exit 1; Chksum="$$(psql --dbname='immich' --username='postgres' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      - postgres
      - "-c"
      - shared_preload_libraries=vectors.so
      - "-c"
      - search_path="$$user", public, vectors
      - "-c"
      - logging_collector=on
      - "-c"
      - max_wal_size=2GB
      - "-c"
      - shared_buffers=512MB
      - "-c"
      - wal_compression=on
    restart: unless-stopped
    networks:
      - immich
networks:
  immich:
    name: immich
x-casaos:
  architectures:
    - amd64
  main: immich-server
  store_app_id: immich
  category: Gallery
  author: ServaLabs
  developer: ServaLabs
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore-Play@main/Apps/immich/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Immich/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Immich/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Immich/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Immich/thumbnail.png
  description:
    en_us: |
      Gallery is a self-hosted media solution for organizing, viewing, and sharing personal photos and videos across devices. It features auto-backup from mobile devices, a responsive web interface, and support for features like face recognition and 4K playback. Perfect for home users seeking private, fast, and flexible media access. Ideal for private cloud deployments with full control and no external dependencies.
  tagline:
    en_us: Self-hosted media management solution
  title:
    en_us: Gallery
  port_map: "2283"
  scheme: http
  index: /
