name: big-bear-budibase
services:
  big-bear-budibase:
    container_name: big-bear-budibase
    image: budibase/budibase:3.5.3
    restart: unless-stopped
    volumes:
      - /files/.apps/$AppID/data:/data
    ports:
      - "8080:80"
    x-casaos:
      volumes:
        - container: /data
          description:
            en_us: "Container Path: /data"
      ports:
        - container: "80"
          description:
            en_us: "Container Port: 80"
x-casaos:
  architectures:
    - amd64
  main: big-bear-budibase
  description:
    en_us: A flexible low-code platform for building internal tools, apps, and workflows in minutes. Easily connect databases like PostgreSQL or MongoDB and integrate REST APIs. Ideal for teams needing quick custom apps with minimal coding. Offers a sleek UI and efficient automation capabilities.
  tagline:
    en_us: Build internal tools fast.
  developer: ServaLabs
  author: ServaLabs
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/budibase.png
  thumbnail: ""
  title:
    en_us: Internak Tools Builder
  category: BigBearCasaOS
  port_map: "8080"
