name: big-bear-obsidian-livesync
services:
  app:
    container_name: obsidian-livesync
    image: couchdb:3.4.3
    restart: unless-stopped
    volumes:
      - /files/.apps/$AppID/data:/opt/couchdb/data
      - /files/.apps/$AppID/config:/opt/couchdb/etc/local.ini
    environment:
      - COUCHDB_USER=casaos
      - COUCHDB_PASSWORD=casaos
    ports:
      - "5984:5984"
    x-casaos:
      volumes:
        - container: /opt/couchdb/data
          description:
            en_us: "Container Path: /opt/couchdb/data"
        - container: /opt/couchdb/etc/local.ini
          description:
            en_us: "Container Path: /opt/couchdb/etc/local.ini"
      ports:
        - container: "5984"
          description:
            en_us: "Container Port: 5984"
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: |
      Notes Sync Database is a self-hosted CouchDB instance designed for real-time syncing of markdown files across devices.
      Ideal for powering services like Obsidian LiveSync, it ensures a seamless, secure, and private sync experience.
      With easy deployment and minimal configuration, it's perfect for local-first note-taking workflows.
  tagline:
    en_us: Real-time sync database for markdown-based notes.
  developer: ServaLabs
  author: ServaLabs
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/obsidian.png
  thumbnail: ""
  title:
    en_us: Notes Sync Database
  category: BigBearCasaOS
  port_map: "5984"
  tips:
    before_install:
      en_us: |
        Run this script before installing the Notes Sync Database app:

        ```
        bash -c "$(wget -qLO - https://raw.githubusercontent.com/bigbeartechworld/big-bear-scripts/master/generate-obsidian-livesync-local-ini/run.sh)"
        ```

        After running this script, you need to restart the container.
