name: stremio
services:
  stremio:
    container_name: stremio
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      - NO_CORS=1
    image: tsaridas/stremio-docker:v1.1.117
    volumes:
      - type: bind
        source: /files/.apps/$AppID/config
        target: /root/.stremio-server
    ports:
      - target: 11470
        published: "11470"
        protocol: tcp
      - target: 8080
        published: "8100"
        protocol: tcp
    restart: unless-stopped
    network_mode: bridge
    privileged: false
    x-casaos:
      ports:
        - container: "11470"
          description:
            en_us: Server Port
          protocol: tcp
        - container: "8100"
          description:
            en_us: WebUI HTTPS Port
          protocol: tcp
      envs:
        - container: NO_CORS
          description:
            en_us: CORS config.
      volumes:
        - container: /root/.stremio-server
          description:
            en_us: Stremio config directory.
x-casaos:
  architectures:
    - amd64
  main: stremio
  author: ServaLabs
  category: Media
  description:
    en_us: |
      Streamer is a powerful streaming hub for organizing and accessing your favorite media. It supports diverse content types and integrates easily across devices.
      With a modern interface and advanced playback capabilities, it enables high-quality viewing experiences, including support for 4K HDR content.
      Designed for privacy and performance, it's the go-to solution for centralized home media streaming.
  developer: ServaLabs
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Stremio/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Stremio/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Stremio/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Stremio/screenshot-3.png
  tagline:
    en_us: A powerful media center for all your entertainment needs.
  tips:
    before_install:
      en_us: |
        You need to set streaming server to http://YOUR_SERVER_IP:11470 on Settings -> Streaming -> Url
  title:
    en_us: Streamer
  index: /
  port_map: "8100"
