name: stremio
services:
    stremio:
        cpu_shares: 90
        command: []
        container_name: content-streamer
        deploy:
            resources:
                limits:
                    memory: "2147483648"
        devices:
            - /dev/dri:/dev/dri
        environment:
            NO_CORS: "1"
        hostname: content-streamer
        image: tsaridas/stremio-docker:v1.1.111
        labels:
            icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Stremio/icon.png
        network_mode: bridge
        ports:
            - target: 11470
              published: "11470"
              protocol: tcp
            - target: 8080
              published: "8100"
              protocol: tcp
        restart: unless-stopped
        volumes:
            - type: bind
              source: /lab/Apps/Content Streamer
              target: /root/.stremio-server
        x-casaos:
            envs:
                - container: NO_CORS
                  description:
                    en_us: CORS config.
                    pt_br: Configuração do CORS
                    zh_cn: CORS配置
            ports:
                - container: "11470"
                  description:
                    en_us: Server Port
                    pt_br: Porta do Server
                    zh_cn: Server HTTP端口
                  protocol: tcp
                - container: "8100"
                  description:
                    en_us: WebUI HTTPS Port
                    pt_br: Porta da WebUI
                    zh_cn: WebUI HTTPS端口
                  protocol: tcp
            volumes:
                - container: /root/.stremio-server
                  description:
                    en_us: Stremio config directory.
                    pt_br: Diretório de configurações do Stremio
                    zh_cn: Stremio配置目录
networks:
    default:
        name: stremio_default
x-casaos:
    architectures:
        - amd64
        - arm64
    author: joaobosconff
    category: Media
    description:
        en_us: Stremio offers a secure, modern and seamless entertainment experience. With its easy-to-use interface and diverse content library, including 4K HDR support, users can enjoy their favorite movies and TV shows across all their devices. And with its commitment to security, Stremio is the ultimate choice for a worry-free, high-quality streaming experience.
        pt_br: Stremio oferece uma experiência de entretenimento segura, moderna e perfeita. Com sua interface fácil de usar e uma biblioteca de conteúdo diversificada, incluindo suporte a 4K HDR, os usuários podem curtir seus filmes e programas de TV favoritos em todos os seus dispositivos. E com seu compromisso com a segurança, o Stremio é a escolha definitiva para uma experiência de streaming sem preocupações e de alta qualidade.
        zh_cn: Stremio提供了一个安全、现代且无缝的娱乐体验。通过其易于使用的界面和多样化的内容库，包括对4K HDR的支持，用户可以在所有设备上欣赏他们喜爱的电影和电视节目。并且凭借其对安全的承诺，Stremio是一个无忧、高质量的流媒体体验的最佳选择。
    developer: Andreas Tsarida / Stremio
    hostname: ""
    icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Stremio/icon.png
    index: /
    is_uncontrolled: false
    main: stremio
    port_map: "8100"
    scheme: http
    screenshot_link:
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Stremio/screenshot-1.png
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Stremio/screenshot-2.png
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Stremio/screenshot-3.png
    store_app_id: stremio
    tagline:
        en_us: Stremio is a modern media center that gives you the freedom to watch everything you want.
        pt_br: Stremio é um centro de mídia moderno que lhe dá a liberdade de assistir a tudo o que você quiser.
        zh_cn: 现代的媒体中心，提供自由观看您喜欢的一切的体验。
    tips:
        before_install:
            en_us: |
                You need to set streaming server to http://YOUR_SERVER_IP:11470 on Settings -> Streaming -> Url
            pt_br: |
                É necessário colocar a url do servidor de streaming para http://IP DO SEU SERVIDOR:11470 em Configurações -> Streaming -> Url
            zh_cn: |
                您需要在 "设置"->"流媒体"->"网址 "中将流媒体服务器设置为 http://您的服务器 IP:11470
    title:
        custom: Content Streamer
        en_us: Stremio
        pt_br: Stremio
        zh_cn: Stremio
