name: big-bear-romm
services:
  big-bear-romm:
    image: rommapp/romm:3.8.1
    container_name: big-bear-romm
    environment:
      - DB_HOST=big-bear-rommdb
      - DB_PORT=3306
      - DB_USER=romm-user
      - DB_NAME=romm
      - DB_PASSWD=casaos
      - ROMM_AUTH_SECRET_KEY=<secret key>
      - IGDB_CLIENT_ID=<igdb client id>
      - IGDB_CLIENT_SECRET=<igdb client secret>
      - MOBYGAMES_API_KEY=<moby api key>
      - STEAMGRIDDB_API_KEY=<sgdb api key>
      - ENABLE_RESCAN_ON_FILESYSTEM_CHANGE=true
      - ENABLE_SCHEDULED_RESCAN=true
      - ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB=true
    volumes:
      - /files/.apps/$AppID/resources:/romm/resources
      - /files/.apps/$AppID/redis-data:/redis-data
      - /files/.apps/$AppID/library:/romm/library
      - /files/.apps/$AppID/assets:/romm/assets
      - /files/.apps/$AppID/config:/romm/config
      - /files/.apps/$AppID/logs:/romm/logs
    ports:
      - 9841:8080
    depends_on:
      - big-bear-rommdb
    restart: "unless-stopped"
    networks:
      - big-bear-romm-network
    x-casaos:
      envs:
        - container: DB_HOST
          description:
            en_us: "Database Host: romm_db"
        - container: DB_PORT
          description:
            en_us: "Database Port: 3306"
        - container: DB_USER
          description:
            en_us: "Database User: romm-user"
        - container: DB_NAME
          description:
            en_us: "Database Name: romm"
        - container: DB_PASSWD
          description:
            en_us: "Database Password: casaos"
        - container: IGDB_CLIENT_ID
          description:
            en_us: "IGDB Client ID (Optional): Generate an ID and SECRET in IGDB"
        - container: IGDB_CLIENT_SECRET
          description:
            en_us: "IGDB Client Secret (Optional): https://api-docs.igdb.com/#account-creation"
        - container: MOBYGAMES_API_KEY
          description:
            en_us: "MobyGames API Key (Optional): Generate at https://www.mobygames.com/info/api/"
        - container: STEAMGRIDDB_API_KEY
          description:
            en_us: "SteamGridDB API Key (Optional): See https://github.com/rommapp/romm/wiki/Generate-API-Keys#steamgriddb"
        - container: ROMM_AUTH_SECRET_KEY
          description:
            en_us: "Authentication Secret Key: <secret key>"
        - container: ENABLE_RESCAN_ON_FILESYSTEM_CHANGE
          description:
            en_us: "Rescan On Filesystem Change: true"
        - container: ENABLE_SCHEDULED_RESCAN
          description:
            en_us: "Scheduled Rescan: true"
        - container: ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB
          description:
            en_us: "Scheduled Update Switch TitleDB: true"
      volumes:
        - container: /romm/resources
          description:
            en_us: "Container Path: /romm/resources"
        - container: /romm/library
          description:
            en_us: "Container Path: /romm/library"
        - container: /romm/assets
          description:
            en_us: "Container Path: /romm/assets"
        - container: /romm/config
          description:
            en_us: "Container Path: /romm/config"
        - container: /romm/logs
          description:
            en_us: "Container Path: /romm/logs"
      ports:
        - container: "8080"
          description:
            en_us: "Container Port: 8080"
  big-bear-rommdb:
    image: mariadb:latest
    container_name: big-bear-rommdb
    environment:
      - MYSQL_ROOT_PASSWORD=casaos
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=casaos
    volumes:
      - /files/.apps/$AppID/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    restart: "unless-stopped"
    networks:
      - big-bear-romm-network
    x-casaos:
      envs:
        - container: MYSQL_ROOT_PASSWORD
          description:
            en_us: "MySQL root password: casaos"
        - container: MYSQL_DATABASE
          description:
            en_us: "MySQL database: romm"
        - container: MYSQL_USER
          description:
            en_us: "MySQL user: romm-user"
        - container: MYSQL_PASSWORD
          description:
            en_us: "MySQL password: casaos"
      volumes:
        - container: /var/lib/mysql
          description:
            en_us: "Container Path: /var/lib/mysql"
      ports:
        - container: "3306"
          description:
            en_us: "Container Port: 3306"
networks:
  big-bear-romm-network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
  main: big-bear-romm
  description:
    en_us: |
      Game Library is a modern ROM manager for retro game collections. It organizes and enriches your game metadata, providing a sleek interface with artwork and details from over 400 supported platforms. With support for metadata APIs, scheduled rescans, and deep customization, it brings your retro collection to life. Perfect for enthusiasts looking to streamline their gaming archive.
  tagline:
    en_us: Game Library
  developer: ServaLabs
  author: ServaLabs
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/romm.png
  thumbnail: ""
  title:
    en_us: Game Library
  category: BigBearCasaOS
  port_map: "9841"
  tips:
    before_install:
      en_us: |
        Run this script before installing the application:

        ```
        bash -c "$(wget -qLO - https://raw.githubusercontent.com/bigbeartechworld/big-bear-scripts/master/generate-romm-config/run.sh)"
        ```

        After running this script, restart the container.