name: uptimekuma
services:
  uptimekuma:
    image: louislam/uptime-kuma:1.23.16
    deploy:
      resources:
        reservations:
          memory: 128M
    network_mode: bridge
    ports:
      - target: 3001
        published: "3001"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /files/.apps/$AppID/data
        target: /app/data
    x-casaos:
      ports:
        - container: "3001"
          description:
            en_us: WebUI Port
      volumes:
        - container: /app/data
          description:
            en_us: Service monitor data directory.
    container_name: uptimekuma
x-casaos:
  architectures:
    - amd64
  main: uptimekuma
  author: ServaLabs
  category: Network
  description:
    en_us: |
      Monitoring Agent is a sleek, self-hosted service uptime monitor. It helps you track and visualize the status of websites and services in real time. With customizable alerting, built-in notifications, and an elegant UI, it empowers you to stay on top of your infrastructure health. Ideal for both personal and professional use.
  developer: ServaLabs
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/UptimeKuma/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/UptimeKuma/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/UptimeKuma/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/UptimeKuma/screenshot-3.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/UptimeKuma/screenshot-4.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/UptimeKuma/screenshot-5.jpg
  tagline:
    en_us: A sleek self-hosted monitoring tool
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/UptimeKuma/thumbnail.png
  tips: {}
  title:
    en_us: Monitoring Agent
  index: /
  port_map: "3001"
