version: "3.7"
name: invokeai

services:
  invokeai:
    container_name: InvokeAI
    image: ghcr.io/invoke-ai/invokeai:latest
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          memory: 48000M
        reservations:
          devices:
            - capabilities:
                - gpu
              driver: nvidia
              count: -1
    volumes:       
      - /DATA/AppData/invokeai:/root/.invokeai
    network_mode: bridge
    restart: unless-stopped
    # CasaOS specific configuration for volume and port descriptions
    x-casaos:
      volumes:
        - container: /root/.invokeai
          description:
            en_us: Container path for InvokeAI configuration and models

# CasaOS specific application metadata and configurations
x-casaos:
  architectures:
    - amd64
    - arm64
  main: InvokeAI
  description:
    en_us: InvokeAI is a leading creative engine for Stable Diffusion models, featuring an optimized pipeline, user-friendly interface, and advanced features for creative image generation and editing.
  tagline:
    en_us: Advanced Stable Diffusion Interface
  developer: invoke-ai
  author: JustSerdar
  icon: https://raw.githubusercontent.com/justserdar/ZimaOS-AppStore/main/Apps/invoke/logo.png
  thumbnail: https://raw.githubusercontent.com/justserdar/ZimaOS-AppStore/main/Apps/invoke/logo.png
  title:
    en_us: InvokeAI
  category: Generative AI
  port_map: "9090"
  scheme: http
  index: /
  tips:
    before_install:
      en_us: |
        Make sure you have enough disk space for models and NVIDIA drivers installed if using GPU acceleration.
        First startup may take several minutes while downloading initial models.

