name: big-bear-dashdot
services:
  app:
    image: mauricenino/dashdot:5.9.2
    ports:
      - "3001:3001"
    volumes:
      - /files/.apps/$AppID/host:/mnt/host
    privileged: true
    x-casaos:
      volumes:
        - container: /mnt/host
          description:
            en_us: "Container Path: /mnt/host"
      ports:
        - container: "3001"
          description:
            en_us: "Container Port: 3001"
x-casaos:
  architectures:
    - amd64
  main: app
  author: ServaLabs
  developer: ServaLabs
  category: BigBearCasaOS
  description:
    en_us: A sleek and responsive server dashboard for monitoring system health. Ideal for small home servers, it provides real-time stats including CPU, RAM, storage, and network usage. Simple to deploy and user-friendly with clean visuals.
  tagline:
    en_us: A modern and lightweight server dashboard
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/dashdot.png
  thumbnail: ""
  title:
    en_us: Dashboard
  port_map: "3001"
