name: big-bear-flowise
services:
  big-bear-flowise:
    container_name: big-bear-flowise
    image: flowiseai/flowise:2.2.6
    restart: unless-stopped
    entrypoint: /bin/sh -c "sleep 3; flowise start"
    environment:
      - PORT=8009
      - FLOWISE_USERNAME=bigbear
      - FLOWISE_PASSWORD=b0f91e4c-9d4b-4375-bc9b-9b57667ce7ab
      - FLOWISE_SECRETKEY_OVERWRITE="true"
      - LANGCHAIN_ENDPOINT=""
      - LANGCHAIN_API_KEY=""
      - LANGCHAIN_PROJECT=""
      - LANGCHAIN_TRACING_V2=""
      - DISABLE_FLOWISE_TELEMETRY="true"
      - DATABASE_PATH=/root/.flowise
      - APIKEY_PATH=/root/.flowise
      - SECRETKEY_PATH=/root/.flowise/logs
      - LOG_PATH=/root/.flowise
    ports:
      - "8009:8009"
    volumes:
      - /files/.apps/$AppID/data:/root/.flowise
    x-casaos:
      envs:
        - container: "PORT"
          description:
            en_us: "Container Port: 8009"
        - container: "FLOWISE_USERNAME"
          description:
            en_us: "Username: bigbear"
        - container: "FLOWISE_PASSWORD"
          description:
            en_us: "Password: b0f91e4c-9d4b-4375-bc9b-9b57667ce7ab"
        - container: "FLOWISE_SECRETKEY_OVERWRITE"
          description:
            en_us: "Secretkey Overwrite: true"
        - container: "LANGCHAIN_ENDPOINT"
          description:
            en_us: "Langchain Endpoint: "
        - container: "LANGCHAIN_API_KEY"
          description:
            en_us: "Langchain API Key: "
        - container: "LANGCHAIN_PROJECT"
          description:
            en_us: "Langchain Project: "
        - container: "LANGCHAIN_TRACING_V2"
          description:
            en_us: "Langchain Tracing V2: "
        - container: "DISABLE_FLOWISE_TELEMETRY"
          description:
            en_us: "Disable Flowise Telemetry: true"
        - container: "DATABASE_PATH"
          description:
            en_us: "Database Path: /root/.flowise"
        - container: "APIKEY_PATH"
          description:
            en_us: "Apikey Path: /root/.flowise"
        - container: "SECRETKEY_PATH"
          description:
            en_us: "Secretkey Path: /root/.flowise/logs"
        - container: "LOG_PATH"
          description:
            en_us: "Log Path: /root/.flowise"
      volumes:
        - container: "/root/.flowise"
          description:
            en_us: "Container Path: /root/.flowise"
      ports:
        - container: "8009"
          description:
            en_us: "Container Port: 8009"
x-casaos:
  architectures:
    - amd64
  main: big-bear-flowise
  description:
    en_us: |
      LLM Orchestrator provides a simple visual interface for building flows with large language models and other AI components. It helps users quickly prototype and deploy AI agent systems using a drag-and-drop UI. The system is open-source, low-code, and designed to speed up LLM app development workflows.
  tagline:
    en_us: Visual LLM Builder
  developer: ServaLabs
  author: ServaLabs
  icon: "https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos/Apps/flowise/logo.png"
  thumbnail: ""
  title:
    en_us: LLM Orchestrator
  category: BigBearCasaOS
  port_map: "8009"
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-flowise-to-bigbearcasaos/1989?u=dragonfire1119