name: coolstore-navidrome
services:
  navidrome:
    image: deluan/navidrome:sha-4f9418b
    ports:
      - '4533:4533'
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ''
    volumes:
      - type: bind
        source: /files/.apps/$AppID/data
        target: /data
      - type: bind
        source: /files/40 Entertainment/43 Music/
        target: /music
        read_only: true
x-casaos:
  architectures:
    - amd64
  main: navidrome
  description:
    en_us: |
      Music-Server lets you access and stream your personal music collection from anywhere using a sleek web interface or compatible mobile apps. 
      It supports a wide range of audio formats and provides powerful tools like automatic library scanning, smart playlists, and user session controls.
      Whether you're at home or on the go, Music-Server offers a fast, intuitive, and customizable way to enjoy your music.
  tagline:
    en_us: Stream your personal music collection from anywhere via web and mobile apps.
  developer: ServaLabs
  author: ServaLabs
  icon: https://pbs.twimg.com/profile_images/1310671419240583170/5lhEh5KF_400x400.jpg
  thumbnail: https://pbs.twimg.com/profile_images/1310671419240583170/5lhEh5KF_400x400.jpg
  title:
    en_us: Music Server
  category: Coolstore
  port_map: '4533'
