name: linuxserver-endlessh
services:
  app:
    image: linuxserver/endlessh:version-dfe44eb2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: Asia/Kolkata
      MSDELAY: ''
      MAXLINES: ''
      MAXCLIENTS: ''
      LOGFILE: ''
      BINDFAMILY: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: MSDELAY
          description:
            en_us: The endless banner is sent one line at a time. This is the delay in milliseconds between individual lines.
        - container: MAXLINES
          description:
            en_us: The length of each line is randomized. This controls the maximum length of each line. Shorter lines may keep clients on for longer if they give up after a certain number of bytes.
        - container: MAXCLIENTS
          description:
            en_us: Maximum number of connections to accept at a time. Connections beyond this are not immediately rejected, but will wait in the queue.
        - container: LOGFILE
          description:
            en_us: By default, the app logs to container log. If this is set to true, the log will be output to file under /config/logs/endlessh (/config needs to be mapped).
        - container: BINDFAMILY
          description:
            en_us: By default, the app binds to IPv4 and IPv6 addresses. Set it to 4 or 6 to bind to IPv4 only or IPv6 only, respectively. Leave blank to bind to both.
      volumes:
        - container: /config
          description:
            en_us: Required if `LOGFILE` is set to `true`.
        - container: /config
          description:
            en_us: Required if `LOGFILE` is set to `true`.
      ports:
        - container: '22'
          description:
            en_us: ssh port
    ports:
      - target: 22
        published: 2222
        protocol: tcp
    volumes:
      - type: bind
        source: /files/.apps/$AppID/config
        target: /config
      - type: bind
        source: /files/.apps/$AppID/config
        target: /config
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: 
    en_us: SSH Honeypot simulates an SSH server and slowly sends an infinite banner to connecting clients. It helps deter brute-force attacks and distract unauthorized users by consuming their resources. Deploy it alongside your real SSH server on a different port for maximum effectiveness.
  tagline:
    en_us: Lightweight SSH tarpit to waste attackers' time.
  developer: ServaLabs
  author: ServaLabs
  icon: https://github.com/linuxserver/docker-templates/raw/master/linuxserver.io/img/openssh-server-logo.png
  thumbnail: https://github.com/linuxserver/docker-templates/raw/master/linuxserver.io/img/openssh-server-logo.png
  title:
    en_us: SSH Honeypot
  category: LinuxServer.io
  project_url: https://github.com/skeeto/endlessh
  port_map: '2222'
