name: readerr
services:
  app:
    image: hotio/readarr:nightly-0.4.13.2754
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ''
        - container: PGID
          description:
            en_us: ''
        - container: TZ
          description:
            en_us: ''
    ports:
      - target: 8787
        published: 8787
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /portainer/downloads
        target: /downloads
      - type: bind
        source: /portainer/books
        target: /books
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: Readarr usent server
  tagline:
    en_us: Readarr Usent Server
  developer: ''
  author: WisdomSky
  icon: https://raw.githubusercontent.com/Readarr/Readarr/develop/Logo/128.png
  thumbnail: https://raw.githubusercontent.com/Readarr/Readarr/develop/Logo/128.png
  title:
    en_us: Readarr
  category: Coolstore
  port_map: '8787'
