name: big-bear-mealie
services:
  app:
    container_name: big-bear-mealie
    image: hkotel/mealie:v2.8.0
    restart: unless-stopped
    volumes:
      - /files/.apps/$AppID/data:/app/data
    ports:
      - "9925:9000"
    x-casaos:
      volumes:
        - container: /app/data
          description:
            en_us: "Container Path: /app/data"
      ports:
        - container: "9000"
          description:
            en_us: "Container Port: 9000"
x-casaos:
  architectures:
    - amd64
  main: app
  author: ServaLabs
  developer: ServaLabs
  category: BigBearCasaOS
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/mealie.png
  thumbnail: ""
  title:
    en_us: Recipe Manager
  description:
    en_us: |
      Recipe Manager is a self-hosted platform for organizing, storing, and sharing recipes. It supports importing recipes from URLs, editing with a rich UI, and meal planning. Ideal for individuals and families who want a centralized place to manage culinary ideas. The application features a modern frontend with a robust backend API.
  tagline:
    en_us: Recipe Manager
  port_map: "9925"
  tips:
    before_install:
      en_us: |
        Read this: https://community.bigbeartechworld.com/t/added-mealie-to-bigbearcasaos/587