name: big-bear-dozzle
services:
    app:
        cpu_shares: 90
        command: []
        container_name: logger
        deploy:
            resources:
                limits:
                    memory: "16524509184"
        hostname: big-bear-dozzle
        image: amir20/dozzle:v8.11.9
        labels:
            icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos/Apps/dozzle/logo.png
        networks:
            default: null
        ports:
            - mode: ingress
              target: 8080
              published: "8888"
              protocol: tcp
        restart: unless-stopped
        volumes:
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
              bind:
                create_host_path: true
        x-casaos:
            ports:
                - container: "8080"
                  description:
                    en_us: 'Container Port: 8080'
            volumes:
                - container: /var/run/docker.sock
                  description:
                    en_us: 'Container Path: /var/run/docker.sock'
networks:
    default:
        name: big-bear-dozzle_default
x-casaos:
    architectures:
        - amd64
        - arm64
    author: BigBearTechWorld
    category: BigBearCasaOS
    description:
        en_us: Dozzle is a real-time log viewer for docker containers.
    developer: amir20
    hostname: ""
    icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos/Apps/dozzle/logo.png
    index: /
    is_uncontrolled: false
    main: app
    port_map: "8888"
    scheme: http
    store_app_id: big-bear-dozzle
    tagline:
        en_us: Dozzle is a real-time log viewer for docker containers.
    thumbnail: ""
    title:
        custom: Logger
        en_us: Dozzle
