name: linuxserver-duplicati
services:
  app:
    image: linuxserver/duplicati:2.1.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: Asia/Kolkata
      SETTINGS_ENCRYPTION_KEY: ''
      CLI_ARGS: ''
      DUPLICATI__WEBSERVICE_PASSWORD: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: SETTINGS_ENCRYPTION_KEY
          description:
            en_us: Encryption key for settings database. Minimum 8 characters, alphanumeric.
        - container: CLI_ARGS
          description:
            en_us: Optionally specify any CLI variables you want to launch the app with
        - container: DUPLICATI__WEBSERVICE_PASSWORD
          description:
            en_us: Password for the webui. If left unset will default to changeme and can be changed from the webui settings.
    ports:
      - target: 8200
        published: 8200
        protocol: tcp
    volumes:
      - type: bind
        source: /files/.apps/$AppID/config
        target: /config
      - type: bind
        source: /files
        target: /files
x-casaos:
  architectures:
    - amd64
  main: app
  author: ServaLabs
  developer: ServaLabs
  category: LinuxServer.io
  title:
    en_us: Backup Client
  description:
    en_us: |
      Backup Client is a secure and efficient tool for managing encrypted, incremental backups to local and remote destinations. It supports cloud providers and standard file transfer protocols like FTP, SSH, WebDAV, and more. With a web-based interface, it makes setting up and scheduling backups simple. The tool also includes compression and versioning to optimize storage space and protect against data loss.
  tagline:
    en_us: Secure, encrypted, incremental backup client for local and cloud storage.
  icon: https://github.com/linuxserver/docker-templates/raw/master/linuxserver.io/img/duplicati-icon.png
  thumbnail: https://github.com/linuxserver/docker-templates/raw/master/linuxserver.io/img/duplicati-icon.png
  port_map: "8200"
