name: linuxserver-qbittorrent
services:
  app:
    image: linuxserver/qbittorrent:5.0.4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: Asia/Kolkata
      WEBUI_PORT: ''
      TORRENTING_PORT: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: WEBUI_PORT
          description:
            en_us: for changing the port of the web UI, see below for explanation
        - container: TORRENTING_PORT
          description:
            en_us: for changing the port of tcp/udp connection, see below for explanation
    ports:
      - target: 8080
        published: 9981
        protocol: tcp
      - target: 6881
        published: 6881
        protocol: tcp
      - target: 6881
        published: 6881
        protocol: udp
    volumes:
      - type: bind
        source: /files/.apps/$AppID/config
        target: /config
      - type: bind
        source: /files/Downloads
        target: /downloads
      - type: bind
        source: /files/.apps/$AppID/theme
        target: /theme
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: |
      Torrent Client is a fast, open-source BitTorrent client designed for simplicity and efficiency. It supports all major BitTorrent features including magnet links, sequential downloading, and bandwidth scheduling.
      With a clean web interface and remote access support, it provides users with complete control over torrent activity from any device.
      Ideal for users looking to manage large downloads with ease while maintaining low system resource usage.
  tagline:
    en_us: A modern, lightweight torrent client with a sleek web interface.
  developer: ServaLabs
  author: ServaLabs
  icon: https://github.com/linuxserver/docker-templates/raw/master/linuxserver.io/img/qbittorrent-icon.png
  thumbnail: https://github.com/linuxserver/docker-templates/raw/master/linuxserver.io/img/qbittorrent-icon.png
  title:
    en_us: Torrent Client
  category: LinuxServer.io
  port_map: '9981'
