name: linuxserver-netbootxyz
services:
  app:
    image: linuxserver/netbootxyz:0.7.5
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: Asia/Kolkata
      MENU_VERSION: ''
      PORT_RANGE: ''
      SUBFOLDER: ''
      NGINX_PORT: ''
      WEB_APP_PORT: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: MENU_VERSION
          description:
            en_us: Specify a specific version of boot files you want to use from NETBOOT.XYZ (unset pulls latest)
        - container: PORT_RANGE
          description:
            en_us: Specify the port range tftp will use for data transfers (see Wikipedia)
        - container: SUBFOLDER
          description:
            en_us: Specify a subfolder if running this behind a reverse proxy (IE /proxy/)
        - container: NGINX_PORT
          description:
            en_us: Specify a different internal port for the asset server
        - container: WEB_APP_PORT
          description:
            en_us: Specify a different internal port for the configuration UI
    ports:
      - target: 3000
        published: 2507
        protocol: tcp
      - target: 69
        published: 69
        protocol: udp
      - target: 8080
        published: 8059
        protocol: tcp
    volumes:
      - type: bind
        source: /files/.apps/$AppID/config
        target: /config
      - type: bind
        source: /files/.assets
        target: /assets
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: |
      Net Boot enables you to network boot operating systems and utilities from a centralized environment. 
      It leverages iPXE to deliver a BIOS-accessible menu, making OS selection and booting seamless and media-free. 
      Useful for system recovery, deployments, or live environments, it's ideal for managing boot workflows across machines.
  tagline:
    en_us: Seamlessly boot operating systems and tools over the network without needing boot media.
  developer: ServaLabs
  author: ServaLabs
  icon: https://netboot.xyz/images/netboot.xyz.gif
  thumbnail: https://netboot.xyz/images/netboot.xyz.gif
  title:
    en_us: Net Boot
  category: LinuxServer.io
  port_map: '2507'
