name: big-bear-flcontainers-guacamole

services:
  app:
    image: flcontainers/guacamole:1.5.5
    container_name: big-bear-flcontainers-guacamole
    restart: always
    environment:
      tz: "Asia/Kolkata"
      EXTENSIONS: "auth-totp,auth-ldap"
    ports:
      - 8080:8080

    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: User Timezone
        - container: EXTENSIONS
          description:
            en_us: Extensions to be enabled
      ports:
        - container: "8080"
          description:
            en_us: "Container Port: 8080"

x-casaos:
  architectures:
    - amd64
  main: app
  author: ServaLabs
  developer: ServaLabs
  description:
    en_us: |
      Remote Desktop Gateway provides secure, client-less access to remote machines using standard protocols such as RDP, VNC, and SSH. 
      Access is done through a web browser without the need for plugins, ensuring ease of use and compatibility. 
      It's ideal for managing multiple desktops and servers in a centralized manner. 
      Enable extensions for added security and integration options like TOTP and LDAP.
  tagline:
    en_us: Web-based Remote Desktop Access.
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/guacamole.png
  thumbnail: ""
  title:
    en_us: Remote Desktop Gateway
  category: BigBearCasaOS
  port_map: "8080"
