name: linuxserver-remmina
services:
  app:
    image: linuxserver/remmina:1.4.35
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: Asia/Kolkata
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /files/.apps/$AppID/config
        target: /config
x-casaos:
  architectures:
    - amd64
  main: app
  author: ServaLabs
  developer: ServaLabs
  category: LinuxServer.io
  description:
    en_us: |
      Remote Desktop is a versatile client that enables users to connect and interact with multiple remote machines from a single interface. It supports popular network protocols including RDP, VNC, SPICE, SSH, and EXEC, ensuring broad compatibility with various server types. Designed for system administrators and remote workers, it offers an intuitive GTK-based interface and seamless experience across diverse screen sizes. Ideal for accessing remote desktops securely and efficiently.
  tagline:
    en_us: Access and manage remote desktops using a powerful multi-protocol client.
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/remmina-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/remmina-icon.png
  title:
    en_us: Remote Desktop
  port_map: "3000"
