name: linuxserver-rustdesk
services:
  app:
    image: linuxserver/rustdesk:1.3.8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: Asia/Kolkata
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 3000
        published: 6514
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /files/.apps/$AppID/config
        target: /config
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Remote Access is a lightweight and secure self-hosted tool for desktop control and screen sharing. It offers end-to-end encryption and requires minimal setup. Ideal for remote support or accessing personal machines securely from anywhere.
  tagline:
    en_us: Secure and fast remote desktop access with end-to-end encryption.
  developer: ServaLabs
  author: ServaLabs
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/rustdesk-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/rustdesk-logo.png
  title:
    en_us: Remote Access
  category: LinuxServer.io
  port_map: "6514"
