name: linuxserver-monica
services:
  app:
    image: linuxserver/monica:4.1.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: Asia/Kolkata
      DB_HOST: ''
      DB_PORT: ''
      DB_USERNAME: ''
      DB_PASSWORD: ''
      DB_DATABASE: ''
      APP_URL: ''
      TRUSTED_PROXIES: ''
      APP_ENV: ''
      APP_DISABLE_SIGNUP: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: DB_HOST
          description:
            en_us: Mariadb DB server hostname.
        - container: DB_PORT
          description:
            en_us: Mariadb DB server port.
        - container: DB_USERNAME
          description:
            en_us: Mariadb DB user.
        - container: DB_PASSWORD
          description:
            en_us: Mariadb DB password.
        - container: DB_DATABASE
          description:
            en_us: Mariadb DB name.
        - container: APP_URL
          description:
            en_us: The URL you will use to access Monica including protocol, and port where appropriate.
        - container: TRUSTED_PROXIES
          description:
            en_us: Set to the IP or netmask covering your reverse proxy, if running behind one. Set to ` to trust all IPs (do not* use * if exposed to the internet).
        - container: APP_ENV
          description:
            en_us: Set to production when exposing the container to anyone else; this also makes https mandatory.
        - container: APP_DISABLE_SIGNUP
          description:
            en_us: Set to false to enable new account sign-ups.
    ports:
      - target: 80
        published: 7841
        protocol: tcp
    volumes:
      - type: bind
        source: /files/.apps/$AppID/config
        target: /config
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Relationship Manager is a self-hosted personal CRM that helps you keep track of the people in your life. It allows you to store detailed profiles, track interactions, and maintain important dates, giving you a better way to nurture relationships. Built for individuals who value connection, it's like having a digital rolodex with superpowers.
  tagline:
    en_us: Self-hosted personal relationship manager.
  developer: ServaLabs
  author: ServaLabs
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/monica-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/monica-logo.png
  title:
    en_us: Relationship Manager
  category: LinuxServer.io
  port_map: '7841'
