name: big-bear-cloudflared-web

services:
  big-bear-cloudflared-web:
    container_name: big-bear-cloudflared-web
    image: wisdomsky/cloudflared-web:2025.2.1
    restart: unless-stopped
    network_mode: host
    environment:
      - WEBUI_PORT=14333
      - EDGE_IP_VERSION=auto
      - PROTOCOL=auto
      - METRICS_ENABLE=false
      - METRICS_PORT=60123
      - BASIC_AUTH_USER=admin
      - BASIC_AUTH_PASS=password
    x-casaos:
      envs:
        - container: WEBUI_PORT
          description:
            en_us: "Web UI Port"
        - container: EDGE_IP_VERSION
          description:
            en_us: "Edge IP Version"
        - container: PROTOCOL
          description:
            en_us: "Protocol"
        - container: METRICS_ENABLE
          description:
            en_us: "Metrics Enable"
        - container: METRICS_PORT
          description:
            en_us: "Metrics Port"
        - container: BASIC_AUTH_USER
          description:
            en_us: "Basic Auth User"
        - container: BASIC_AUTH_PASS
      ports:
        - container: "14333"
          description:
            en_us: "Container Port: 14333"
x-casaos:
  architectures:
    - amd64
  main: big-bear-cloudflared-web
  author: ServaLabs
  developer: ServaLabs
  description:
    en_us: |
      Tunnel Manager provides an easy-to-use web interface for controlling Cloudflare Tunnels. 
      With built-in support for Cloudflared CLI, it simplifies remote access setup by letting users start and stop tunnels without command line operations. 
      Ideal for quick deployments and managing secure connections via Cloudflare's network.
  tagline:
    en_us: Manage Cloudflare Tunnels effortlessly
  title:
    en_us: Cloudflare Tunnels
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/cloudflare.png
  thumbnail: ""
  category: BigBearCasaOS
  port_map: "14333"
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-cloudflared-web-to-bigbearcasaos/2275?u=dragonfire1119
