name: big-bear-it-tools
services:
  app:
    container_name: big-bear-it-tools
    image: corentinth/it-tools:2023.11.2-7d94e11
    restart: unless-stopped
    ports:
      - "9888:80"
    x-casaos:
      ports:
        - container: "80"
          description:
            en_us: "Container Port: 80"
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: A collection of web-based tools for developers including encoders, converters, formatters, and more. This app is designed for convenience and speed, running entirely in-browser without requiring external services. Great for quick tasks, debugging, and daily productivity.
  tagline:
    en_us: Developer Toolbox
  developer: ServaLabs
  author: ServaLabs
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/it-tools.png
  thumbnail: ""
  title:
    en_us: Developer Toolbox
  category: Tools
  port_map: "9888"
