name: frigate
services:
  frigate:
    container_name: frigate
    entrypoint: >
      bash -c '
        if [ ! -f "/config/config.yml" ]; then
          echo -n "No config file found. Create one... "
          {
            echo "# config generated on $(date +%Y.%m.%d\ %H:%M:%S)"
            echo "mqtt:"
            echo "  enabled: False"
            echo ""
            echo "cameras:"
            echo "  sample_camera: # <------ Name the camera"
            echo "    ffmpeg:"
            echo "      inputs:"
            echo "        - path: rtsp://192.168.255.10/stream # <----- The stream you want to use for detection"
            echo "          roles:"
            echo "            - detect"
            echo "    detect:"
            echo "      enabled: False # <---- disable detection until you have a working camera feed"
            echo "      width: 1280 # <---- update for your camera resolution"
            echo "      height: 720 # <---- update for your camera resolution"
          } > /config/config.yml
          if [ $? -eq 0 ]; then
            echo "done."
          else
            echo "error."
            exit 1
          fi
        fi
        /init'
    privileged: true
    image: ghcr.io/blakeblackshear/frigate:stable
    labels:
      icon: https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/Frigate/icon.png
    network_mode: bridge
    ports:
      - target: 5000
        published: "5000"
        protocol: tcp
      - target: 8554
        published: "8554"
        protocol: tcp
      - target: 8555
        published: "8555"
        protocol: tcp
      - target: 8555
        published: "8555"
        protocol: udp
    restart: unless-stopped
    healthcheck:
      test: curl --fail -s http://localhost:5000/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    shm_size: "64mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/renderD128
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: bind
        source: /files/.apps/$AppID/config
        target: /config
      - type: bind
        source: /files/.apps/$AppID/media
        target: /media/frigate
    x-casaos:
      ports:
        - container: "5000"
          description:
            en_us: "Web GUI port"
        - container: "8554"
          description:
            en_us: "RTSP feeds"
        - container: "8555"
          description:
            en_us: "WebRTC over tcp and udp"
      volumes:
        - container: /config
          description:
            en_us: Contains all configuration files.
        - container: /media/frigate
          description:
            en_us: Contains database and all media files.
x-casaos:
  architectures:
    - amd64
  author: ServaLabs
  category: Surveillance
  description:
    en_us: |
      Camera Monitor provides powerful AI-based local video surveillance using motion detection and object recognition. Designed for real-time processing, it leverages hardware acceleration and supports Coral TPU for enhanced performance.
      With integrated MQTT support, it easily connects with other systems like Home Assistant. The app enables 24/7 recording, intelligent event-based detection, and re-streaming via RTSP or WebRTC for low-latency live views.
      It's a fully local solution prioritizing performance, privacy, and integration flexibility.
  developer: ServaLabs
  icon: https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/Frigate/icon.png
  index: /
  main: frigate
  port_map: "5000"
  project_url: https://github.com/mr-manuel/CasaOS-HomeAutomation-AppStore
  screenshot_link:
    - https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/Frigate/screenshot-1.png
    - https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/Frigate/screenshot-2.png
    - https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/Frigate/screenshot-3.png
    - https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/Frigate/screenshot-4.png
    - https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/Frigate/screenshot-5.png
    - https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/Frigate/screenshot-6.png
    - https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/Frigate/screenshot-7.png
  store_app_id: frigate
  tagline:
    en_us: |
      A powerful local NVR with AI detection. Designed for real-time camera monitoring and seamless smart home integration.
  thumbnail: https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/Frigate/icon.png
  tips:
    before_install:
      en_us: |
        This app uses ports `5000/tcp`, `8554/tcp`, `8555/tcp`, and `8555/udp`. Configure your cameras and detection rules after installation.
  title:
    en_us: AI Surveillance
