name: big-bear-beszel

services:
  big-bear-beszel:
    container_name: big-bear-beszel
    image: henrygd/beszel:0.10.2
    restart: unless-stopped

    volumes:
      - /files/.apps/$AppID/data:/beszel_data

    ports:
      - "8090:8090"

    x-casaos:
      volumes:
        - container: "/beszel_data"
          description:
            en_us: "Beszel Data"
      ports:
        - container: "8090"
          description:
            en_us: "Container Port: 8090"

x-casaos:
  architectures:
    - amd64
  main: big-bear-beszel
  description:
    en_us: A compact and efficient resource monitoring dashboard that tracks historical server metrics, container usage, and system health. Useful for admins who want simple, self-hosted stats with minimal setup.
  tagline:
    en_us: Lightweight Server Resource Monitor
  developer: ServaLabs
  author: ServaLabs
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos/Apps/beszel/logo.jpg
  thumbnail: ""
  title:
    en_us: Resource Monitor
  category: BigBearCasaOS
  port_map: "8090"
