name: linuxserver-spotube
services:
  app:
    image: linuxserver/spotube:4.0.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: Asia/Kolkata
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 3000
        published: 8441
        protocol: tcp
    volumes:
      - type: bind
        source: /files/.apps/$AppID/config
        target: /config
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: |
      Music-Streamer is a lightweight, privacy-focused music streaming client that interfaces with Spotify’s API and uses alternative sources like YouTube or Piped to stream content. 
      It supports cross-platform usage and works without the need for a Spotify Premium account. 
      The interface is intuitive and responsive, making it easy to enjoy music anywhere while staying in control of your data.
  tagline:
    en_us: A privacy-friendly music streaming client that doesn't require Spotify Premium.
  developer: ServaLabs
  author: ServaLabs
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/spotube-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/spotube-logo.png
  title:
    en_us: Music Streamer
  category: LinuxServer.io
  port_map: "8441"
