name: pi-alert
services:
  app:
    image: jokobsk/pi.alert:25
    restart: always
    network_mode: host
    environment:
      PUID: $PUID
      PGID: $PGID
      HOST_USER_ID: $PUID
      HOST_USER_GID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ''
        - container: PGID
          description:
            en_us: ''
    ports:
      - target: 20211
        published: 20211
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /home/pi/pialert/config
      - type: bind
        source: /DATA/AppData/$AppID/db
        target: /home/pi/pialert/db
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: WIFI / LAN intruder detector
  tagline:
    en_us: Wifi / Lan Intruder Detector
  developer: ''
  author: WisdomSky
  icon: https://raw.githubusercontent.com/pucherot/Pi.Alert/main/docs/img/1_devices.jpg
  thumbnail: https://raw.githubusercontent.com/pucherot/Pi.Alert/main/docs/img/1_devices.jpg
  title:
    en_us: Pi.alert
  category: Coolstore
  port_map: '20211'
