name: homebox
services:
  homebox:
    cpu_shares: 90
    command: []
    container_name: homebox
    deploy:
      resources:
        limits:
          memory: 15759M
    environment:
      - HBOX_OPTIONS_ALLOW_ANALYTICS=false
      - TZ=Asia/Kolkata
    hostname: homebox
    image: ghcr.io/sysadminsmedia/homebox:latest
    labels:
      icon: https://homebox.software/lilbox.svg
    ports:
      - target: 7745
        published: "3100"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /files/.apps/$AppID/data
        target: /data
    x-casaos:
      ports:
        - container: "7745"
          description:
            en_us: Web UI Port
      volumes:
        - container: /data
          description:
            en_us: Persistent data storage
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  architectures:
    - amd64
  author: ServaLabs
  category: Management
  description:
    en_us: >
      Inventory Manager is a self-hosted tool for organizing and tracking household items, electronics, tools, and other assets.
      With a clean web interface, it enables easy categorization, tagging, and search functionality.
      It's ideal for keeping track of serial numbers, warranties, and purchase details in one accessible place.
      Designed for personal home use with simple setup and powerful features.
  developer: ServaLabs
  hostname: ""
  icon: https://homebox.software/lilbox.svg
  index: /
  is_uncontrolled: false
  main: homebox
  port_map: "3100"
  scheme: http
  store_app_id: homebox
  tagline:
    en_us: Personal Inventory Management System
  title:
    custom: ""
    en_us: Inventory Manager
