name: big-bear-rallly
services:
  big-bear-rallly:
    container_name: big-bear-rallly
    image: lukevella/rallly:3.11.2
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://rallly:f87c7126-f816-47ef-9193-2e5eec763fcd@big-bear-rallly-db/big-bear-rallly
      - SECRET_PASSWORD=0f6f292d-c78c-4709-920d-e3b6361eb5b5
      - NEXT_PUBLIC_BASE_URL=http://[YOUR_CASAOS_IP]:3000
      - NOREPLY_EMAIL=noreply@example.com
      - SUPPORT_EMAIL=support@example.com
      - SMTP_HOST=[YOUR_CASAOS_IP]
      - SMTP_PORT=1025
      - SMTP_SECURE=
      - SMTP_USER=
      - SMTP_PWD=
      - SMTP_TLS_ENABLED=
      - ALLOWED_EMAILS=
    ports:
      - "3000:3000"
    networks:
      - big_bear_rally_network
    depends_on:
      big-bear-rallly-db:
        condition: service_healthy
    x-casaos:
      envs:
        - container: DATABASE_URL
          description:
            en_us: "Database URL: postgres://rallly:*****@big-bear-rallly-db/big-bear-rallly"
        - container: SECRET_PASSWORD
          description:
            en_us: "Secret password for application security"
        - container: NEXT_PUBLIC_BASE_URL
          description:
            en_us: "Frontend URL"
        - container: NOREPLY_EMAIL
          description:
            en_us: "Email used for sending no-reply messages"
        - container: SUPPORT_EMAIL
          description:
            en_us: "Support contact email"
        - container: SMTP_HOST
          description:
            en_us: "SMTP server host"
        - container: SMTP_PORT
          description:
            en_us: "SMTP server port"
        - container: SMTP_SECURE
          description:
            en_us: "SMTP server security"
        - container: SMTP_USER
          description:
            en_us: "SMTP server username"
        - container: SMTP_PWD
          description:
            en_us: "SMTP server password"
        - container: SMTP_TLS_ENABLED
          description:
            en_us: "SMTP server TLS enabled"
        - container: ALLOWED_EMAILS
          description:
            en_us: "Allowed emails for the application"
  big-bear-rallly-db:
    container_name: big-bear-rallly-db
    image: postgres:14
    restart: unless-stopped
    volumes:
      - /files/.apps/$AppID/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=f87c7126-f816-47ef-9193-2e5eec763fcd
      - POSTGRES_DB=big-bear-rallly
      - POSTGRES_USER=rallly
    networks:
      - big_bear_rally_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rallly"]
      interval: 5s
      timeout: 5s
      retries: 5
    x-casaos:
      envs:
        - container: POSTGRES_PASSWORD
          description:
            en_us: "Database password"
        - container: POSTGRES_DB
          description:
            en_us: "Database name"
        - container: POSTGRES_USER
          description:
            en_us: "Database user"
networks:
  big_bear_rally_network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
  main: big-bear-rallly
  author: ServaLabs
  developer: ServaLabs
  category: BigBearCasaOS
  description:
    en_us: |
      Scheduler is a self-hosted, collaborative tool for coordinating events and availability. It helps users find the best meeting times by polling participants. Built with a clean interface and simple setup, it's ideal for planning get-togethers, meetings, or any group decision-making.
  tagline:
    en_us: Scheduler
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/rallly.png
  thumbnail: ""
  title:
    en_us: Scheduler
  port_map: "3000"
  tips:
    before_install:
      en_us: |
        Before you install read this: https://community.bigbeartechworld.com/t/added-rallly-to-bigbearcasaos/1012#instructions-3