name: casaos-toolbox
services:
  app:
    image: wisdomsky/casaos-toolbox:0.2
    restart: unless-stopped
    network_mode: host
    environment:
      FORCE_HTTPS: false
      WEBUI_PORT: 8088
      DB_HOST: 0.0.0.0
      DB_PORT: 33066
      DB_DATABASE: casaos
      DB_USERNAME: casaos
      DB_PASSWORD: casaos
    volumes:
      - /files/.apps/$AppID/bin:/usr/bin/casaos-cli
      - /files/.apps/$AppID/config:/casaos/gateway.ini
      - /files/.apps/$AppID/apps:/casaos/apps
      - /files/.apps/$AppID/www:/casaos/www
  db:
    image: mariadb:11.7.2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: casaos
      MYSQL_DATABASE: casaos
      MYSQL_USER: casaos
      MYSQL_PASSWORD: casaos
    ports:
      - target: 3306
        published: '33066'
        protocol: tcp
    volumes:
      - /files/.apps/$AppID/mysql:/var/lib/mysql
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: |
      Utility-Hub extends your CasaOS setup with advanced tools and management capabilities. 
      It integrates seamlessly with CasaOS, offering centralized access to core components like databases, gateways, and CLI tools. 
      With a focus on enhancing system control and developer productivity, Utility-Hub is perfect for advanced users and tinkerers alike.
  tagline:
    en_us: Enhance CasaOS with developer utilities and tools.
  developer: ServaLabs
  author: ServaLabs
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-Coolstore@main/Apps/casaos-toolbox/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-Coolstore@main/Apps/casaos-toolbox/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-Coolstore@main/Apps/casaos-toolbox/screenshot-3.png
  icon: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-Coolstore@main/Apps/casaos-toolbox/icon.png
  thumbnail: https://cdn.jsdelivr.net/gh/WisdomSky/CasaOS-Coolstore@main/Apps/casaos-toolbox/icon.png
  category: Coolstore
  title:
    en_us: Toolbox
  port_map: '8088'
