name: big-bear-coolify
services:
  big-bear-coolify:
    container_name: big-bear-coolify
    image: ghcr.io/coollabsio/coolify:4.0.0-beta.380
    restart: unless-stopped
    environment:
      - PHP_MEMORY_LIMIT="512M"
      - APP_ID="coolify"
      - APP_ENV="production"
      - APP_DEBUG="false"
      - APP_NAME="Coolify"
      - APP_KEY="base64:lSStPbXB/yW6cxXIz8fauQ937PbSUktTdIf7R05szQ4="
      - APP_URL="http://[CASAOS_IP]:8000"
      - DB_CONNECTION="pgsql"
      - DB_HOST="big-bear-coolify-postgres"
      - DB_PORT="5432"
      - DB_DATABASE="coolify"
      - DB_USERNAME="coolify"
      - DB_PASSWORD="f1986213-9d72-4c36-bbd4-adca2f414fa1"
      - QUEUE_CONNECTION="redis"
      - REDIS_HOST="big-bear-coolify-redis"
      - REDIS_PASSWORD="9e3df6aa-ea48-4e59-a9c4-59798f1ba9b4"
      - HORIZON_BALANCE="100"
      - HORIZON_MAX_PROCESSES="10"
      - HORIZON_BALANCE_MAX_SHIFT="10"
      - HORIZON_BALANCE_COOLDOWN="10"
      - SSL_MODE="off"
      - PHP_PM_CONTROL="dynamic"
      - PHP_PM_START_SERVERS="1"
      - PHP_PM_MIN_SPARE_SERVERS="1"
      - PHP_PM_MAX_SPARE_SERVERS="10"
      - PUSHER_HOST="big-bear-coolify-soketi"
      - PUSHER_BACKEND_HOST="big-bear-coolify-soketi"
      - PUSHER_PORT="6001"
      - PUSHER_BACKEND_PORT="6001"
      - PUSHER_SCHEME="http"
      - PUSHER_APP_ID="coolify"
      - PUSHER_APP_KEY=
      - PUSHER_APP_SECRET=
      - AUTOUPDATE=true
      - SELF_HOSTED=true
      - SSH_MUX_PERSIST_TIME=3600
      - FEEDBACK_DISCORD_WEBHOOK=
      - WAITLIST=
      - SUBSCRIPTION_PROVIDER=
      - STRIPE_API_KEY=
      - STRIPE_WEBHOOK_SECRET=
      - STRIPE_PRICE_ID_BASIC_MONTHLY=
      - STRIPE_PRICE_ID_BASIC_YEARLY=
      - STRIPE_PRICE_ID_PRO_MONTHLY=
      - STRIPE_PRICE_ID_PRO_YEARLY=
      - STRIPE_PRICE_ID_ULTIMATE_MONTHLY=
      - STRIPE_PRICE_ID_ULTIMATE_YEARLY=
      - STRIPE_PRICE_ID_DYNAMIC_MONTHLY=
      - STRIPE_PRICE_ID_DYNAMIC_YEARLY=
      - STRIPE_PRICE_ID_BASIC_MONTHLY_OLD=
      - STRIPE_PRICE_ID_BASIC_YEARLY_OLD=
      - STRIPE_PRICE_ID_PRO_MONTHLY_OLD=
      - STRIPE_PRICE_ID_PRO_YEARLY_OLD=
      - STRIPE_PRICE_ID_ULTIMATE_MONTHLY_OLD=
      - STRIPE_PRICE_ID_ULTIMATE_YEARLY_OLD=
      - STRIPE_EXCLUDED_PLANS=
    volumes:
      - /files/.apps/$AppID/ssh:/var/www/html/storage/app/ssh
      - /files/.apps/$AppID/applications:/var/www/html/storage/app/applications
      - /files/.apps/$AppID/databases:/var/www/html/storage/app/databases
      - /files/.apps/$AppID/services:/var/www/html/storage/app/services
      - /files/.apps/$AppID/backups:/var/www/html/storage/app/backups
      - /files/.apps/$AppID/webhooks-during-maintenance:/var/www/html/storage/app/webhooks-during-maintenance
      - /files/.apps/$AppID/logs:/var/www/html/storage/logs
    ports:
      - "8000:80"
    healthcheck:
      test: curl --fail http://127.0.0.1:80/api/health || exit 1
      interval: 5s
      retries: 10
      timeout: 2s
    depends_on:
      big-bear-coolify-postgres:
        condition: service_healthy
      big-bear-coolify-redis:
        condition: service_healthy
    networks:
      - big_bear_coolify_network
  big-bear-coolify-postgres:
    container_name: big-bear-coolify-postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - /files/.apps/$AppID/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "coolify"
      POSTGRES_PASSWORD: "f1986213-9d72-4c36-bbd4-adca2f414fa1"
      POSTGRES_DB: "coolify"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coolify", "-d", "coolify"]
      interval: 5s
      retries: 10
      timeout: 2s
    networks:
      - big_bear_coolify_network
  big-bear-coolify-redis:
    container_name: big-bear-coolify-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    command: [ ... ]
    environment:
      REDIS_PASSWORD: "9e3df6aa-ea48-4e59-a9c4-59798f1ba9b4"
    volumes:
      - /files/.apps/$AppID/redis:/data
    healthcheck:
      test: redis-cli ping
      interval: 5s
      retries: 10
      timeout: 2s
    networks:
      - big_bear_coolify_network
  big-bear-coolify-soketi:
    container_name: big-bear-coolify-soketi
    image: quay.io/soketi/soketi:1.6-16-alpine
    ports:
      - "6001:6001"
      - "6002:6002"
    environment:
      SOKETI_DEBUG: "false"
      SOKETI_DEFAULT_APP_ID: ""
      SOKETI_DEFAULT_APP_KEY: ""
      SOKETI_DEFAULT_APP_SECRET: ""
    healthcheck:
      test: wget -qO- http://127.0.0.1:6001/ready || exit 1
      interval: 5s
      retries: 10
      timeout: 2s
    networks:
      - big_bear_coolify_network
networks:
  big_bear_coolify_network:
    name: big_bear_coolify_network
    driver: bridge
  coolify:
    external: true
x-casaos:
  architectures:
    - amd64
  main: big-bear-coolify
  author: ServaLabs
  developer: ServaLabs
  category: BigBearCasaOS
  description:
    en_us: App Platform is a self-hosted PaaS that allows you to deploy and manage apps and services effortlessly. With database, Redis, and real-time socket support, it's ideal for managing production infrastructure in one place. Modern UI and scalable backend make it perfect for personal or enterprise use.
  tagline:
    en_us: Self-hosted app platform
  title:
    en_us: Deployer
  icon: "https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos/Apps/coolify/logo.png"
  thumbnail: ""
  port_map: "8000"
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-coolify-to-casaos/2186?u=dragonfire1119