name: linuxserver-syncthing
services:
  app:
    image: linuxserver/syncthing:1.29.3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: Asia/Kolkata
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 8384
        published: 8384
        protocol: tcp
      - target: 22000
        published: 22000
        protocol: tcp
      - target: 22000
        published: 22000
        protocol: udp
      - target: 21027
        published: 21027
        protocol: udp
    volumes:
      - type: bind
        source: /files/.apps/$AppID/
        target: /config
      - type: bind
        source: /files
        target: /files
    container_name: app
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: |
      File Sync is a decentralized synchronization tool for files across devices. It ensures your data remains private, secure, and always available without relying on third-party cloud providers. Ideal for seamless and automatic sync between desktops, servers, and mobile devices. This self-hosted solution supports encrypted connections, version control, and granular sharing.
  tagline:
    en_us: Decentralized, secure, and automatic file synchronization across your devices.
  developer: ServaLabs
  author: ServaLabs
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/syncthing-banner.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/syncthing-banner.png
  title:
    en_us: File Sync
  category: LinuxServer.io
  port_map: "8384"