name: linuxserver-readme-sync
services:
  app:
    image: linuxserver/readme-sync:84f2d0c3-ls27
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/readme-sync/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: This container needs special attention. Please check https://hub.docker.com/r/linuxserver/readme-sync for details.
  tagline:
    en_us: This container needs special attention. Please check https://hub. Docker. Com/r/linuxserver/readme-sync for details.
  developer: LinuxServer.io
  author: WisdomSky
  icon: ''
  thumbnail: ''
  title:
    en_us: Readme sync
  category: LinuxServer.io
  port_map: '80'
