name: big-bear-anse
services:
  big-bear-anse:
    container_name: big-bear-anse
    image: ddiu8081/anse:v1.1.11
    restart: unless-stopped
    environment:
      - PORT=8014
    ports:
      - "8014:8014"
    x-casaos:
      envs:
        - container: PORT
          description:
            en_us: "Port: 8014"
      ports:
        - container: "8014"
          description:
            en_us: "Container Port: 8014"
x-casaos:
  architectures:
    - amd64
  main: big-bear-anse
  author: ServaLabs
  developer: ServaLabs
  description:
    en_us: |
      Chat-UI is a lightweight and modern user interface tailored for seamless interaction with various AI chat models. It supports services like ChatGPT, DALL·E, and Stable Diffusion, all within a unified and optimized environment. Designed for speed and simplicity, Chat-UI enhances your workflow with intuitive conversations and dynamic multimedia capabilities.
  tagline:
    en_us: Modern UI for multi-model AI chats.
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos/Apps/anse/logo.jpg
  thumbnail: ""
  title:
    en_us: Chat UI
  category: BigBearCasaOS
  port_map: "8014"
