name: big-bear-semaphore
services:
  big-bear-semaphore:
    container_name: big-bear-semaphore
    image: semaphoreui/semaphore:v2.13.0
    restart: unless-stopped
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: big-bear-semaphore-db
      SEMAPHORE_DB_PORT: "3306"
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: semaphore
      SEMAPHORE_ADMIN_PASSWORD: password
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@example.com
      SEMAPHORE_ADMIN: admin
      TZ: Asia/Kolkata
    volumes:
      - /files/.apps/$AppID/home:/etc/semaphore
      - /files/.apps/$AppID/lib:/var/lib/semaphore
    ports:
      - "3000:3000"
    networks:
      - big-bear-semaphore-network
    x-casaos:
      volumes:
        - container: /etc/semaphore
          description:
            en_us: "Container Path: /etc/semaphore"
        - container: /var/lib/semaphore
          description:
            en_us: "Container Path: /var/lib/semaphore"
      ports:
        - container: "3000"
          description:
            en_us: "Container Port: 3000"
  big-bear-semaphore-db:
    container_name: big-bear-semaphore-db
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - /files/.apps/$AppID/mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "semaphore"
      MYSQL_USER: "semaphore"
      MYSQL_PASSWORD: "semaphore"
    networks:
      - big-bear-semaphore-network
    x-casaos:
      volumes:
        - container: /var/lib/mysql
          description:
            en_us: "Container Path: /var/lib/mysql"
      ports:
        - container: "3306"
          description:
            en_us: "Container Port: 3306"
networks:
  big-bear-semaphore-network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
  main: big-bear-semaphore
  author: ServaLabs
  developer: ServaLabs
  category: BigBearCasaOS
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/semaphore.png
  thumbnail: ""
  title:
    en_us: Automation UI
  description:
    en_us: |
      Automation UI is a clean, user-friendly interface for managing Ansible playbooks and automation tasks. This self-hosted tool simplifies deployment workflows with access control and real-time failure alerts. Perfect for teams managing complex server infrastructures.
  tagline:
    en_us: Web UI for automation tasks
  port_map: "3000"
