name: metube-youtubedl
services:
    app:
        cpu_shares: 90
        command: []
        container_name: ytdl
        deploy:
            resources:
                limits:
                    memory: "16524509184"
        environment:
            DARK_MODE: "true"
            GID: "1000"
            UID: "1000"
        hostname: ytdl
        image: alexta69/metube:2025-03-07
        labels:
            icon: https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/master/Images/ytdlm.png
        networks:
            default: null
        ports:
            - target: 8081
              published: "8081"
              protocol: tcp
        restart: unless-stopped
        volumes:
            - type: bind
              source: /lab/50 Infotainment
              target: /downloads
        x-casaos:
            envs: []
networks:
    default:
        name: metube-youtubedl_default
x-casaos:
    architectures:
        - amd64
        - arm
        - arm64
    author: WisdomSky
    category: Coolstore
    description:
        en_us: Web GUI for youtube-dl with playlist support. Allows you to download videos from YouTube and dozens of other sites (https://ytdl-org.github.io/youtube-dl/supportedsites.html).
    developer: ""
    hostname: ""
    icon: https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/master/Images/ytdlm.png
    index: /
    is_uncontrolled: false
    main: app
    port_map: "8081"
    scheme: http
    store_app_id: metube-youtubedl
    tagline:
        en_us: Web Gui For Youtube-dl With Playlist Support. Allows You To Download Videos From Youtube And Dozens Of Other Sites (https://ytdl-org.github.io/youtube-dl/supportedsites.html).
    thumbnail: https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/master/Images/ytdlm.png
    title:
        custom: YouTube Downloader
        en_us: Metube
