name: dify
services:
    api:
        container_name: dify-api
        depends_on:
            db:
                condition: service_started
                required: true
            redis:
                condition: service_started
                required: true
        environment:
            APP_WEB_URL: ""
            CELERY_BROKER_URL: redis://:difyai123456@redis:6379/1
            CODE_EXECUTION_API_KEY: dify-sandbox
            CODE_EXECUTION_ENDPOINT: http://sandbox:8194
            CODE_MAX_NUMBER: "9223372036854775807"
            CODE_MAX_NUMBER_ARRAY_LENGTH: "1000"
            CODE_MAX_OBJECT_ARRAY_LENGTH: "30"
            CODE_MAX_STRING_ARRAY_LENGTH: "30"
            CODE_MAX_STRING_LENGTH: "80000"
            CODE_MIN_NUMBER: "-9223372036854775808"
            CONSOLE_API_URL: ""
            CONSOLE_CORS_ALLOW_ORIGINS: '*'
            CONSOLE_WEB_URL: ""
            DB_DATABASE: dify
            DB_HOST: db
            DB_PASSWORD: difyai123456
            DB_PORT: "5432"
            DB_USERNAME: postgres
            FILES_ACCESS_TIMEOUT: "300"
            FILES_URL: ""
            INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH: "1000"
            INIT_PASSWORD: ""
            LOG_LEVEL: INFO
            MIGRATION_ENABLED: "true"
            MODE: api
            REDIS_DB: "0"
            REDIS_HOST: redis
            REDIS_PASSWORD: difyai123456
            REDIS_PORT: "6379"
            SECRET_KEY: sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U
            SERVICE_API_URL: ""
            SSRF_PROXY_HTTP_URL: http://ssrf_proxy:3128
            SSRF_PROXY_HTTPS_URL: http://ssrf_proxy:3128
            STORAGE_LOCAL_PATH: storage
            STORAGE_TYPE: local
            TEMPLATE_TRANSFORM_MAX_LENGTH: "80000"
            VECTOR_STORE: weaviate
            WEAVIATE_API_KEY: WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih
            WEAVIATE_ENDPOINT: http://weaviate:8080
            WEB_API_CORS_ALLOW_ORIGINS: '*'
        image: langgenius/dify-api:0.12.1
        labels:
            icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Dify/icon.png
        networks:
            dify: null
            ssrf_proxy_network: null
        restart: unless-stopped
        volumes:
            - type: bind
              source: /DATA/AppData/$AppID/data/app/api/storage
              target: /app/api/storage
              bind:
                create_host_path: true
    config:
        container_name: dify-config
        image: ns2kracy/dify-config:latest
        labels:
            icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Dify/icon.png
        networks:
            dify: null
        restart: unless-stopped
        volumes:
            - type: bind
              source: /DATA/AppData/$AppID/data/nginx
              target: /configs/nginx
            - type: bind
              source: /DATA/AppData/$AppID/data/ssrf_proxy
              target: /configs/ssrf_proxy
            - type: bind
              source: /DATA/AppData/$AppID/data/sandbox
              target: /configs/sandbox
    db:
        command:
            - postgres
            - -c
            - max_connections=100
            - -c
            - shared_buffers=128MB
            - -c
            - work_mem=4MB
            - -c
            - maintenance_work_mem=64MB
            - -c
            - effective_cache_size=4096MB
        container_name: dify-db
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            PGUSER: postgres
            POSTGRES_DB: dify
            POSTGRES_PASSWORD: difyai123456
        healthcheck:
            test:
                - CMD
                - pg_isready
            timeout: 3s
            interval: 1s
            retries: 30
        image: postgres:15-alpine
        labels:
            icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Dify/icon.png
        networks:
            dify: null
        restart: unless-stopped
        volumes:
            - type: bind
              source: /DATA/AppData/$AppID/data/db/data
              target: /var/lib/postgresql/data
              bind:
                create_host_path: true
    nginx:
        container_name: dify-nginx
        depends_on:
            api:
                condition: service_started
                required: true
            config:
                condition: service_started
                required: true
            web:
                condition: service_started
                required: true
        image: nginx:latest
        labels:
            icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Dify/icon.png
        networks:
            dify: null
        ports:
            - mode: ingress
              target: 80
              published: "3701"
              protocol: tcp
        restart: unless-stopped
        volumes:
            - type: bind
              source: /DATA/AppData/$AppID/data/nginx
              target: /etc/nginx
              bind:
                create_host_path: true
    redis:
        command:
            - redis-server
            - --requirepass
            - difyai123456
        container_name: dify-redis
        environment:
            REDISCLI_AUTH: difyai123456
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
        image: redis:6-alpine
        labels:
            icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Dify/icon.png
        networks:
            dify: null
        restart: unless-stopped
        volumes:
            - type: bind
              source: /DATA/AppData/$AppID/data/redis/data
              target: /data
              bind:
                create_host_path: true
    sandbox:
        container_name: dify-sandbox
        depends_on:
            config:
                condition: service_started
                required: true
        environment:
            API_KEY: dify-sandbox
            ENABLE_NETWORK: "true"
            GIN_MODE: release
            HTTP_PROXY: http://ssrf_proxy:3128
            HTTPS_PROXY: http://ssrf_proxy:3128
            SANDBOX_PORT: "8194"
            WORKER_TIMEOUT: "15"
        image: langgenius/dify-sandbox:0.2.10
        labels:
            icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Dify/icon.png
        networks:
            ssrf_proxy_network: null
        restart: unless-stopped
        volumes:
            - type: bind
              source: /DATA/AppData/$AppID/data/sandbox/dependencies
              target: /dependencies
              bind:
                create_host_path: true
    ssrf_proxy:
        container_name: dify-ssrf_proxy
        depends_on:
            config:
                condition: service_started
                required: true
        environment:
            COREDUMP_DIR: /var/spool/squid
            HTTP_PORT: "3128"
            REVERSE_PROXY_PORT: "8194"
            SANDBOX_HOST: sandbox
            SANDBOX_PORT: "8194"
        image: ubuntu/squid:latest
        labels:
            icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Dify/icon.png
        networks:
            dify: null
            ssrf_proxy_network: null
        restart: unless-stopped
        volumes:
            - type: bind
              source: /DATA/AppData/$AppID/data/ssrf_proxy
              target: /etc/squid
              bind:
                create_host_path: true
    weaviate:
        container_name: dify-weaviate
        environment:
            AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "false"
            AUTHENTICATION_APIKEY_ALLOWED_KEYS: WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih
            AUTHENTICATION_APIKEY_ENABLED: "true"
            AUTHENTICATION_APIKEY_USERS: hello@dify.ai
            AUTHORIZATION_ADMINLIST_ENABLED: "true"
            AUTHORIZATION_ADMINLIST_USERS: hello@dify.ai
            CLUSTER_HOSTNAME: node1
            DEFAULT_VECTORIZER_MODULE: none
            PERSISTENCE_DATA_PATH: /var/lib/weaviate
            QUERY_DEFAULTS_LIMIT: "25"
        image: semitechnologies/weaviate:1.19.0
        labels:
            icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Dify/icon.png
        networks:
            dify: null
        restart: unless-stopped
        volumes:
            - type: bind
              source: /DATA/AppData/$AppID/data/weaviate
              target: /var/lib/weaviate
              bind:
                create_host_path: true
    web:
        container_name: dify-web
        deploy:
            resources:
                reservations:
                    memory: "2147483648"
        environment:
            APP_API_URL: ""
            CONSOLE_API_URL: ""
        image: langgenius/dify-web:0.12.1
        labels:
            icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Dify/icon.png
        networks:
            dify: null
        restart: unless-stopped
    worker:
        container_name: dify-worker
        depends_on:
            db:
                condition: service_started
                required: true
            redis:
                condition: service_started
                required: true
        environment:
            CELERY_BROKER_URL: redis://:difyai123456@redis:6379/1
            DB_DATABASE: dify
            DB_HOST: db
            DB_PASSWORD: difyai123456
            DB_PORT: "5432"
            DB_USERNAME: postgres
            LOG_LEVEL: INFO
            MODE: worker
            REDIS_DB: "0"
            REDIS_HOST: redis
            REDIS_PASSWORD: difyai123456
            REDIS_PORT: "6379"
            REDIS_USE_SSL: "false"
            SECRET_KEY: sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U
            STORAGE_LOCAL_PATH: storage
            STORAGE_TYPE: local
            VECTOR_STORE: weaviate
            WEAVIATE_API_KEY: WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih
            WEAVIATE_ENDPOINT: http://weaviate:8080
        image: langgenius/dify-api:0.12.1
        labels:
            icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Dify/icon.png
        networks:
            dify: null
            ssrf_proxy_network: null
        restart: unless-stopped
        volumes:
            - type: bind
              source: /DATA/AppData/$AppID/data/app/api/storage
              target: /app/api/storage
              bind:
                create_host_path: true
networks:
    default:
        name: dify_default
    dify:
        name: dify
    ssrf_proxy_network:
        name: dify_ssrf_proxy_network
        driver: bridge
        internal: true
x-casaos:
    architectures:
        - arm64
        - amd64
    author: IceWhaleTech
    category: Chat
    description:
        en_uk: Dify is an open-source large language model (LLM) application development platform. It combines the concepts of Backend-as-a-Service and LLMOps to enable developers to quickly build production-grade generative AI applications. Even non-technical personnel can participate in the definition and data operations of AI applications.
        en_us: Dify is an open-source large language model (LLM) application development platform. It combines the concepts of Backend-as-a-Service and LLMOps to enable developers to quickly build production-grade generative AI applications. Even non-technical personnel can participate in the definition and data operations of AI applications.
        ja_jp: Difyはオープンソースの大規模言語モデル（LLM）開発プラットフォームです。Backend as ServiceとLLMOpsの理念を融合し、開発者が迅速に生成AIアプリケーションを構築できるようにします。技術者でなくても、AIアプリケーションの定義やデータ運用に参加することができます。
        zh_cn: Dify 是一款开源的大语言模型(LLM) 应用开发平台。它融合了后端即服务（Backend as Service）和 LLMOps 的理念，使开发者可以快速搭建生产级的生成式 AI 应用。即使你是非技术人员，也能参与到 AI 应用的定义和数据运营过程中。
    developer: LangGenius
    icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Dify/icon.png
    index: /
    is_uncontrolled: true
    main: web
    port_map: "3701"
    screenshot_link:
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Dify/screenshot-1.png
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Dify/screenshot-2.png
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Dify/screenshot-3.png
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Dify/screenshot-4.png
    store_app_id: dify
    tagline:
        en_us: LLM App Development Platform
    thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Dify/thumbnail.png
    title:
        en_us: Dify
