name: big-bear-wordpress
services:
  app:
    image: wordpress:6.7.2
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: casaos
      WORDPRESS_DB_PASSWORD: casaos
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - /files/.apps/$AppID/html:/var/www/html
    depends_on:
      - db
    x-casaos:
      envs:
        - container: WORDPRESS_DB_HOST
          description:
            en_us: Database host
        - container: WORDPRESS_DB_USER
          description:
            en_us: Database user
        - container: WORDPRESS_DB_PASSWORD
          description:
            en_us: Database password
        - container: WORDPRESS_DB_NAME
          description:
            en_us: Database name
      volumes:
        - container: /var/www/html
          description:
            en_us: "Container Path: /var/www/html"
      ports:
        - container: "80"
          description:
            en_us: "Container Port: 80"
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: casaos
      MYSQL_PASSWORD: casaos
      MYSQL_ROOT_PASSWORD: casaos
    volumes:
      - /files/.apps/$AppID/mysql:/var/lib/mysql
    x-casaos:
      envs:
        - container: MYSQL_DATABASE
          description:
            en_us: Database name
        - container: MYSQL_USER
          description:
            en_us: Database user
        - container: MYSQL_PASSWORD
          description:
            en_us: Database password
        - container: MYSQL_ROOT_PASSWORD
          description:
            en_us: Database root password
      volumes:
        - container: /var/lib/mysql
          description:
            en_us: "Container Path: /var/lib/mysql"
      ports:
        - container: "3306"
          description:
            en_us: "Container Port: 3306"
x-casaos:
  architectures:
    - amd64
  main: app
  author: ServaLabs
  developer: ServaLabs
  category: BigBearCasaOS
  description:
    en_us: A popular content management system that enables you to create and manage websites with ease. It supports themes, plugins, and extensive customization. Ideal for blogs, portfolios, and even online stores. Simple setup, flexible usage, and a vibrant ecosystem make it a go-to choice for web publishing.
  tagline:
    en_us: Website Builder
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/wordpress.png
  thumbnail: ""
  title:
    en_us: Website Builder
  port_map: "8080"
