name: gitea
services:
  gitea:
    environment:
      USER_GID: "1000"
      USER_UID: "1000"
    image: gitea/gitea:1.23.0-rc0-rootless
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
    ports:
      - target: 3000
        published: "3002"
        protocol: tcp
      - target: 22
        published: "222"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /files/.apps/$AppID/data
        target: /data
    x-casaos:
      envs:
        - container: USER_UID
          description:
            en_us: The UID (Unix user ID) of the user that runs Gitea
        - container: USER_GID
          description:
            en_us: The GID (Unix group ID) of the user that runs Gitea
      ports:
        - container: "3000"
          description:
            en_us: WebUI Port
        - container: "22"
          description:
            en_us: SSH Port
      volumes:
        - container: /data
          description:
            en_us: Gitea data directory.
    container_name: gitea
x-casaos:
  architectures:
    - amd64
  main: gitea
  author: ServaLabs
  developer: ServaLabs
  category: Developer
  description:
    en_us: |
      Code Repo is a lightweight, self-hosted solution for managing git repositories, collaborative development, and code reviews. It offers a clean web interface for source code browsing, issue tracking, and team collaboration. Ideal for small teams or individuals, it is easy to deploy and maintain. Features include SSH access, a built-in package registry, CI/CD support, and secure access control.
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Gitea/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Gitea/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Gitea/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Gitea/screenshot-3.png
  tagline:
    en_us: Self-hosted git service and code collaboration
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Gitea/thumbnail.png
  tips:
    before_install:
      en_us: |
        When the App is installed, the first account registered will become the administrator account.
  title:
    en_us: Code Repo
  index: /
  port_map: "3002"