name: big-bear-stirling-pdf
services:
    big-bear-stirling-pdf:
        cpu_shares: 90
        command: []
        container_name: pdf-editor
        deploy:
            resources:
                limits:
                    memory: "16524509184"
        environment:
            CSRF_DISABLED: "false"
            DEFAULT_LOCALE: en-US
            DOCKER_ENABLE_SECURITY: "false"
            INSTALL_BOOK_AND_ADVANCED_HTML_OPS: "false"
            LANGS: en_US
            SECURITY_ENABLE_LOGIN: "true"
            SECURITY_INITIALLOGIN_PASSWORD: saumya20
            SECURITY_INITIALLOGIN_USERNAME: saumya
        hostname: pdf-editor
        image: stirlingtools/stirling-pdf:0.44.2
        labels:
            icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos/Apps/stirling-pdf/logo.png
        networks:
            default: null
        ports:
            - mode: ingress
              target: 8080
              published: "8080"
              protocol: tcp
        restart: unless-stopped
        volumes:
            - type: bind
              source: /lab/Apps/PDF Editor/tessdata
              target: /usr/share/tessdata
              bind:
                create_host_path: true
            - type: bind
              source: /lab/Apps/PDF Editor/configs
              target: /configs
              bind:
                create_host_path: true
        x-casaos:
            envs:
                - container: DOCKER_ENABLE_SECURITY
                  description:
                    en_us: Enable Security Jar for Authentication
                - container: SECURITY_ENABLE_LOGIN
                  description:
                    en_us: Enable Login for Authentication
                - container: SECURITY_INITIALLOGIN_USERNAME
                  description:
                    en_us: Initial admin username
                - container: SECURITY_INITIALLOGIN_PASSWORD
                  description:
                    en_us: Initial admin password
                - container: CSRF_DISABLED
                  description:
                    en_us: Disable CSRF Protection
                - container: DEFAULT_LOCALE
                  description:
                    en_us: Set Default Locale
                - container: INSTALL_BOOK_AND_ADVANCED_HTML_OPS
                  description:
                    en_us: Install Book and Advanced HTML Ops
                - container: LANGS
                  description:
                    en_us: Languages
            ports:
                - container: "8080"
                  description:
                    en_us: 'Container Port: 8080'
            volumes:
                - container: /usr/share/tessdata
                  description:
                    en_us: 'Container Path: /usr/share/tessdata'
                - container: /configs
                  description:
                    en_us: 'Configuration Files Path: /configs'
networks:
    default:
        name: big-bear-stirling-pdf_default
x-casaos:
    architectures:
        - amd64
        - arm64
    author: BigBearTechWorld
    category: BigBearCasaOS
    description:
        en_us: Stirling PDF - Local hosted web based PDF editor
    developer: stirlingtools
    hostname: ""
    icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos/Apps/stirling-pdf/logo.png
    index: /
    is_uncontrolled: false
    main: big-bear-stirling-pdf
    port_map: "8080"
    scheme: http
    store_app_id: big-bear-stirling-pdf
    tagline:
        en_us: Stirling PDF - Local hosted web based PDF editor
    thumbnail: ""
    tips:
        before_install:
            en_us: |
                Read this before installing: https://community.bigbeartechworld.com/t/added-stirling-pdf-to-bigbearcasaos/2265#p-4248-documentation-3
    title:
        custom: PDF Editor
        en_us: Stirling-PDF
